---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: gadget
    repo: oci://ghcr.io/inspektor-gadget/inspektor-gadget/charts
    version: 0.56.0
    releaseName: gadget
    namespace: gadget
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
