---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_02"
  targets:
    # Ingress
    - select:
        kind: Ingress
        name: radarr
      fieldPaths:
        - spec.rules.0.host
        - spec.tls.0.hosts.0
      options:
        delimiter: "."
        index: 1
