---
global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            RADARR__AUTH__METHOD: External
            RADARR__AUTH__REQUIRED: Enabled
            RADARR__APP__THEME: dark
            RADARR__APP__INSTANCENAME: Radarr
            RADARR__LOG__LEVEL: info
            RADARR__LOG__ANALYTICSENABLED: false
            RADARR__POSTGRES__HOST:
              secretKeyRef:
                name: servarr-postgres-app
                key: host
                expandObjectName: false
            RADARR__POSTGRES__PORT:
              secretKeyRef:
                name: servarr-postgres-app
                key: port
                expandObjectName: false
            RADARR__POSTGRES__USER:
              secretKeyRef:
                name: servarr-postgres-app
                key: user
                expandObjectName: false
            RADARR__POSTGRES__PASSWORD:
              secretKeyRef:
                name: servarr-postgres-app
                key: password
                expandObjectName: false
            RADARR__POSTGRES__MAINDB: radarr
            RADARR__POSTGRES__LOGDB: radarr-log
ingress:
  main:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: ingress-proxies
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Movie organizer/manager for usenet and torrent users.
      gethomepage.dev/group: Servarr
      gethomepage.dev/icon: radarr.svg
      gethomepage.dev/name: Radarr
      gethomepage.dev/widget.type: "radarr"
      gethomepage.dev/widget.url: "http://radarr.servarr.svc.cluster.local:7878"
      gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_RADARR_KEY}}`}}"
    hosts:
      - host: "radarr.${FQDN_02}"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - "radarr.${FQDN_02}"
persistence:
  config:
    enabled: true
    mountPath: "/config"
    targetSelector:
      main:
        main:
          mountPath: /config
        exportarr:
          mountPath: /config
          readOnly: true
  mediadata:
    enabled: true
    type: pvc
    mountPath: "/MediaData"
    readOnly: false
    existingClaim: smb-mediadata-rwx
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: metrics
        path: /metrics
    targetSelector: metrics
    prometheusRule:
      enabled: true
