---
global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
podOptions:
  defaultAffinity: false
workload:
  main:
    podSpec:
      annotations:
        secret.reloader.stakater.com/reload: "servarr-postgres-app,servarr-secrets"
      containers:
        main:
          env:
            SONARR__AUTH__METHOD: External
            SONARR__AUTH__REQUIRED: Enabled
            SONARR__AUTH__APIKEY:
              secretKeyRef:
                name: servarr-secrets
                key: sonarr_uhd_api_key
                expandObjectName: false
            SONARR__APP__THEME: auto
            SONARR__APP__INSTANCENAME: Sonarr UHD
            SONARR__LOG__LEVEL: info
            SONARR__LOG__ANALYTICSENABLED: false
            SONARR__POSTGRES__HOST:
              secretKeyRef:
                name: servarr-postgres-app
                key: host
                expandObjectName: false
            SONARR__POSTGRES__PORT:
              secretKeyRef:
                name: servarr-postgres-app
                key: port
                expandObjectName: false
            SONARR__POSTGRES__USER:
              secretKeyRef:
                name: servarr-postgres-app
                key: user
                expandObjectName: false
            SONARR__POSTGRES__PASSWORD:
              secretKeyRef:
                name: servarr-postgres-app
                key: password
                expandObjectName: false
            SONARR__POSTGRES__MAINDB: sonarr-uhd
            SONARR__POSTGRES__LOGDB: sonarr-uhd-log
        exportarr:
          env:
            API_KEY:
              secretKeyRef:
                name: servarr-secrets
                key: sonarr_uhd_api_key
                expandObjectName: false
ingress:
  main:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: ingress-proxies
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Sonarr is an internet PVR for Usenet and Torrents (UHD).
      gethomepage.dev/group: Servarr
      gethomepage.dev/icon: sonarr.svg
      gethomepage.dev/name: Sonarr UHD
      gethomepage.dev/pod-selector: "app.kubernetes.io/instance=sonarr-uhd"
      gethomepage.dev/widget.type: "sonarr"
      gethomepage.dev/widget.url: "http://sonarr-uhd.servarr.svc.cluster.local:8989"
      gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_SONARR_UHD_KEY}}`}}"
    hosts:
      - host: "sonarr-uhd.${FQDN_02}"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - "sonarr-uhd.${FQDN_02}"
persistence:
  config:
    enabled: true
    mountPath: "/config"
    targetSelector:
      main:
        main:
          mountPath: /config
        exportarr:
          mountPath: /config
          readOnly: true
  mediadata:
    enabled: true
    type: pvc
    mountPath: "/MediaData"
    readOnly: false
    existingClaim: smb-mediadata-rwx
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: metrics
        path: /metrics
    targetSelector: metrics
    prometheusRule:
      enabled: true
