---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: env-vars
    envs:
      - /tmp/env-vars.env
replacements:
  - path: ../../base/replacements.yaml
