---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: bookboss-mariadb
  namespace: bookboss
spec:
  database: bookboss
  username: bookboss
  passwordSecretKeyRef:
    name: bookboss-mariadb-user-password
    key: password
    generate: true
  myCnf: |
    [mysqld]
    character_set_server = utf8mb4
    collation_server = utf8mb4_uca1400_ai_ci
    default_authentication_plugin = parsec
    default_time_zone = '+00:00'
  tls:
    enabled: true
    required: true
  storage:
    size: 4Gi
    storageClassName: longhorn
