---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-mediadata-rwx
  namespace: bookboss
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-mediadata
  resources:
    requests:
      storage: 100Ti
