---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: mariadb-operator
    repo: https://mariadb-operator.github.io/mariadb-operator
    version: 26.6.0
    releaseName: mariadb-operator
    namespace: mariadb-system
    valuesFile: ../../base/values/mariadb-operator-values.yaml
    additionalValuesFiles:
      - values/mariadb-operator-values-override.yaml
    includeCRDs: true
