# Provider authentication variables
variable "virtual_environment_endpoint" {
  description = "The URL endpoint for the Proxmox VE API."
  type        = string
}

variable "virtual_environment_api_token" {
  description = "The API token for Proxmox VE."
  type        = string
}

variable "virtual_environment_username" {
  description = "The username for SSH access to Proxmox VE."
  type        = string
}

variable "virtual_environment_password" {
  description = "The password for SSH access to Proxmox VE."
  type        = string
}

# bpg/proxmox -> Resource: proxmox_virtual_environment_vm -> Argument Reference
# https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#argument-reference

# Required variables
variable "node_name" {
  description = "(Required) The name of the node to assign the virtual machine to."
  type        = string
}

# Optional scalar values with documented defaults or nullable
variable "vm_id" {
  description = "(Optional) The VM identifier."
  type        = number
  nullable    = true
  default     = null
}

variable "acpi" {
  description = "(Optional) Whether to enable ACPI (defaults to true)."
  type        = bool
  default     = true
}

variable "bios" {
  description = "(Optional) The BIOS implementation (defaults to 'seabios')."
  type        = string
  default     = "seabios"
}

variable "boot_order" {
  description = "(Optional) Specify a list of devices to boot from in the order they appear in the list (defaults to [])."
  type        = list(string)
  default     = []
}

variable "description" {
  description = "(Optional) The description."
  type        = string
  nullable    = true
  default     = "Generated by Terragrunt"
}

variable "keyboard_layout" {
  description = "(Optional) The keyboard layout (defaults to 'en-us')."
  type        = string
  default     = "en-us"
}

variable "kvm_arguments" {
  description = "(Optional) Arbitrary arguments passed to kvm."
  type        = string
  nullable    = true
  default     = null
}

variable "machine" {
  description = "(Optional) The VM machine type (defaults to 'pc')."
  type        = string
  default     = "pc"
}

variable "migrate" {
  description = "(Optional) Migrate the VM on node change instead of re-creating it (defaults to false)."
  type        = bool
  default     = false
}

variable "name" {
  description = "(Optional) The virtual machine name."
  type        = string
  nullable    = true
  default     = null
}

variable "on_boot" {
  description = "(Optional) Specifies whether a VM will be started during system boot (defaults to true)."
  type        = bool
  default     = true
}

variable "pool_id" {
  description = "(Optional) The identifier for a pool to assign the virtual machine to."
  type        = string
  nullable    = true
  default     = null
}

variable "protection" {
  description = "(Optional) Sets the protection flag of the VM (defaults to false)."
  type        = bool
  default     = false
}

variable "reboot" {
  description = "(Optional) Reboot the VM after initial creation (defaults to false)."
  type        = bool
  default     = false
}

variable "reboot_after_update" {
  description = "(Optional) Reboot the VM after update if needed (defaults to true)."
  type        = bool
  default     = true
}

variable "scsi_hardware" {
  description = "(Optional) The SCSI hardware type (defaults to 'virtio-scsi-single')."
  type        = string
  default     = "virtio-scsi-single"
}

variable "started" {
  description = "(Optional) Whether to start the virtual machine (defaults to true)."
  type        = bool
  default     = true
}

variable "stop_on_destroy" {
  description = "(Optional) Whether to stop rather than shutdown on VM destroy (defaults to false)."
  type        = bool
  default     = false
}

variable "tablet_device" {
  description = "(Optional) Whether to enable the USB tablet device (defaults to true)."
  type        = bool
  default     = true
}

variable "tags" {
  description = "(Optional) A list of tags of the VM."
  type        = list(string)
  default     = ["Terragrunt"]
}

variable "template" {
  description = "(Optional) Whether to create a template (defaults to false)."
  type        = bool
  default     = false
}

variable "timeout_clone" {
  description = "(Optional) Timeout for cloning a VM in seconds (defaults to 1800)."
  type        = number
  default     = 1800
}

variable "timeout_create" {
  description = "(Optional) Timeout for creating a VM in seconds (defaults to 1800)."
  type        = number
  default     = 1800
}

variable "timeout_migrate" {
  description = "(Optional) Timeout for migrating the VM (defaults to 1800)."
  type        = number
  default     = 1800
}

variable "timeout_reboot" {
  description = "(Optional) Timeout for rebooting a VM in seconds (defaults to 1800)."
  type        = number
  default     = 1800
}

variable "timeout_shutdown_vm" {
  description = "(Optional) Timeout for shutting down a VM in seconds (defaults to 1800)."
  type        = number
  default     = 1800
}

variable "timeout_start_vm" {
  description = "(Optional) Timeout for starting a VM in seconds (defaults to 1800)."
  type        = number
  default     = 1800
}

variable "timeout_stop_vm" {
  description = "(Optional) Timeout for stopping a VM in seconds (defaults to 300)."
  type        = number
  default     = 300
}

variable "hook_script_file_id" {
  description = "(Optional) The identifier for a file containing a hook script."
  type        = string
  nullable    = true
  default     = null
}

# Control structure for dynamic blocks
variable "optional_blocks" {
  description = "Map of booleans to enable optional dynamic blocks"
  type = object({
    agent           = bool
    amd_sev         = bool
    audio_device    = bool
    cdrom           = bool
    clone           = bool
    cpu             = bool
    disk            = bool
    efi_disk        = bool
    hostpci         = bool
    network_device  = bool
    numa            = bool
    rng             = bool
    serial_device   = bool
    startup         = bool
    usb             = bool
    vga             = bool
    watchdog        = bool
  })
}

# ----- Agent block -----
variable "agent" {
  description = "(Optional) The QEMU agent configuration."
  type = object({
    enabled = optional(bool, false)
    timeout = optional(string, "15m")
    trim    = optional(bool, false)
    type    = optional(string, "virtio")
  })
  default = null
}

# ----- CPU block -----
variable "cpu" {
  description = "(Optional) The CPU configuration."
  type = object({
    architecture = optional(string, "x86_64")
    cores        = optional(number, 1)
    flags        = optional(list(string))
    hotplugged   = optional(number, 0)
    limit        = optional(number, 0)
    numa         = optional(bool, false)
    sockets      = optional(number, 1)
    type         = optional(string, "qemu64")
    units        = optional(number, 1024)
    affinity     = optional(string)
  })
  default = null
}

# ----- Disk block -----
variable "disks" {
  description = "(Optional) A list of disk configurations."
  type = list(object({
    aio               = optional(string, "io_uring")
    backup            = optional(bool, true)
    cache             = optional(string, "none")
    datastore_id      = optional(string, "local-lvm")
    path_in_datastore = optional(string)
    discard           = optional(string, "ignore")
    file_format       = optional(string)
    file_id           = optional(string)
    interface         = string
    iothread          = optional(bool, false)
    replicate         = optional(bool, true)
    serial            = optional(string)
    size              = optional(number, 8)
    speed = optional(object({
      iops_read             = optional(number)
      iops_read_burstable   = optional(number)
      iops_write            = optional(number)
      iops_write_burstable  = optional(number)
      read                  = optional(number)
      read_burstable        = optional(number)
      write                 = optional(number)
      write_burstable       = optional(number)
    }))
    ssd               = optional(bool, false)
  }))
  default = []
}

# ----- Clone block -----
variable "clones" {
  description = "(Optional) List of cloning configurations."
  type = list(object({
    datastore_id = optional(string)
    node_name    = optional(string)
    retries      = optional(number)
    vm_id        = number
    full         = optional(bool, true)
  }))
  default = []
}

# ----- EFI Disk block -----
variable "efi_disk" {
  description = "(Optional) The EFI disk device (required if `bios` is set to `ovmf`)."
  type = object({
    datastore_id       = optional(string, "local-lvm")
    file_format        = optional(string, "raw")
    type               = optional(string, "2m")
    pre_enrolled_keys  = optional(bool, false)
  })
  default = null
}

# ----- Host PCI block -----
variable "hostpci_devices" {
  description = "(Optional) List of host PCI device mappings."
  type = list(object({
    device   = string
    id       = optional(string)
    mapping  = optional(string)
    mdev     = optional(string)
    pcie     = optional(bool)
    rombar   = optional(bool, true)
    rom_file = optional(string)
    xvga     = optional(bool)
  }))
  default = []
}

# ----- Memory block -----
variable "memory" {
  description = "Memory configuration block"
  type = object({
    dedicated      = optional(number, 512)
    floating       = optional(number, 0)
    shared         = optional(number, 0)
    hugepages      = optional(string)
    keep_hugepages = optional(bool, false)
  })
  default = null
}

# ----- Network Device block -----
variable "network_devices" {
  description = "(Optional) List of network device configurations."
  type = list(object({
    bridge      = optional(string, "vmbr0")
    disconnected = optional(bool, false)
    enabled     = optional(bool, true)
    firewall    = optional(bool, false)
    mac_address = optional(string)
    model       = optional(string, "virtio")
    mtu         = optional(number)
    queues      = optional(number)
    rate_limit  = optional(number)
    vlan_id     = optional(number)
    trunks      = optional(string)
  }))
  default = []
}

# ----- NUMA block -----
variable "numa_devices" {
  description = "(Optional) List of NUMA configurations."
  type = list(object({
    device    = string
    cpus      = string
    memory    = number
    hostnodes = optional(string)
    policy    = optional(string, "preferred")
  }))
  default = []
}

# ----- USB block -----
variable "usb_devices" {
  description = "(Optional) List of USB device mappings."
  type = list(object({
    host    = optional(string)
    mapping = optional(string)
    usb3    = optional(bool, false)
  }))
  default = []
}
