---
# defaults file for btrfs-subvolume

# Path of the btrfs subvolume relative to BTRFS root (no leading slash)
# Matches Proxmox VE format: var/lib/pve/local-btrfs
btrfs_subvol_path: var/lib/pve/local-btrfs
