---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hermes-dashboard
  annotations:
    tailscale.com/proxy-group: ingress-proxies
spec:
  ingressClassName: tailscale
  rules:
    - host: "hermes.${FQDN_02}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hermes-agent
                port:
                  name: dashboard
  tls:
    - hosts:
        - "hermes.${FQDN_02}"
