---
{
  server: {
    # Ingress
    ingress: {
      enabled: true,
      ingressClassName: "tailscale",
      extraTls: [{
        hosts: [
          "argocd",
        ],
      }],
    },
    ingressGrpc: {
      enabled: true,
      ingressClassName: "tailscale",
      extraTls: [{
        hosts: [
          "argocd-grpc",
        ],
      }],
    },
  },
}
