---
server:
  # Ingress
  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Declarative, GitOps continuous delivery tool for Kubernetes.
      gethomepage.dev/group: Operations
      gethomepage.dev/icon: argo-cd.svg
      gethomepage.dev/name: Argo CD
      gethomepage.dev/widget.type: "argocd"
      gethomepage.dev/widget.url: "http://jellyfin.jellyfin.svc.cluster.local:8096"
      gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_ARGOCD_KEY}}"
    extraTls:
      - hosts:
          - "argocd.${FQDN_02}"
  ingressGrpc:
    enabled: true
    ingressClassName: tailscale
    extraTls:
      - hosts:
          - "argocd-grpc.${FQDN_02}"
