---
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
  # Ingress
  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: ingress-proxies
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Declarative, GitOps continuous delivery tool for Kubernetes.
      gethomepage.dev/group: Operations
      gethomepage.dev/icon: argo-cd.svg
      gethomepage.dev/name: Argo CD
      gethomepage.dev/widget.type: "argocd"
      gethomepage.dev/widget.url: "https://argocd-server.argocd.svc.cluster.local"
      gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_ARGOCD_KEY}}`}}"
    extraTls:
      - hosts:
          - "argocd.${FQDN_02}"
  ingressGrpc:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: ingress-proxies
    extraTls:
      - hosts:
          - "argocd-grpc.${FQDN_02}"

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
configs:
  cm:
    url: "https://argocd.${FQDN_02}"
    # Existing OIDC Provider:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#existing-oidc-provider
    oidc.config: |
      name: Kanidm
      issuer: https://auth.${FQDN_01}/oauth2/openid/argocd
      clientID: $oidc.kanidm.clientID
      clientSecret: $oidc.kanidm.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups_name"]
      requestedIDTokenClaims: {"groups_name": {"essential": true}}
      enableUserInfoGroups: true
      userInfoPath: /userinfo
      userInfoCacheExpiration: "5m"
      enablePKCEAuthentication: true
    # API Key for Homepage widget: https://gethomepage.dev/widgets/services/argocd/
    accounts.readonly: apiKey
  rbac:
    scopes: "[groups]"
    policy.csv: |
      g, readonly, role:readonly
      g, argocd-users, role:readonly
      g, argocd-admins, role:admin
