---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../../../../components/kopiur-volume
helmCharts:
  - name: profilarr
    repo: oci://oci.trueforge.org/truecharts
    version: 4.8.0
    releaseName: profilarr
    namespace: servarr
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars-profilarr
    envs:
      - /tmp/env-vars.env
  - name: profilarr-config
    literals:
      - ORIGIN_HOST=profilarr.${FQDN_02}
      - AUTH_HOST=auth.${FQDN_01}
      - ORIGIN=https://profilarr.${FQDN_02}
      - OIDC_DISCOVERY_URL=https://auth.${FQDN_01}/oauth2/openid/profilarr/.well-known/openid-configuration
    options:
      disableNameSuffixHash: true
replacements:
  - path: replacements.yaml
patches:
  - target:
      kind: SnapshotPolicy
      name: kopiur-snapshot-policy
    patch: |-
      - op: replace
        path: /metadata/name
        value: profilarr-snapshot-policy
      - op: replace
        path: /spec/sources/0/pvcSelector/labelSelector/matchLabels/kopiur.home-operations.com~1policy
        value: profilarr-config
  - target:
      kind: SnapshotSchedule
      name: kopiur-snapshot-schedule
    patch: |-
      - op: replace
        path: /metadata/name
        value: profilarr-snapshot-schedule
      - op: replace
        path: /spec/policyRef/name
        value: profilarr-snapshot-policy
  - target:
      kind: Restore
      name: kopiur-restore
    patch: |-
      - op: replace
        path: /metadata/name
        value: profilarr-restore
      - op: replace
        path: /spec/source/fromPolicy/name
        value: profilarr-snapshot-policy
  - target:
      kind: PersistentVolumeClaim
      name: profilarr-config
    patch: |-
      - op: add
        path: /metadata/labels/kopiur.home-operations.com~1policy
        value: profilarr-config
      - op: add
        path: /spec/dataSourceRef
        value:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: profilarr-restore
