---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  template:
    spec:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: immich-gpu-claim
      containers:
        - name: main
          resources:
            claims:
              - name: gpu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  template:
    spec:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: immich-gpu-claim
      containers:
        - name: main
          resources:
            claims:
              - name: gpu
