---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: istiod
    repo: oci://gcr.io/istio-release/charts
    version: 1.26.2
    releaseName: istiod
    namespace: istio-system
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
resources:
  - ../../base
