---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bookorbit-postgres
  namespace: bookorbit
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  postgresql:
    pg_hba:
      - hostssl bookorbit bookorbit all scram-sha-256
      - host bookorbit bookorbit all reject
    extensions:
      - name: pgvector
        image:
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie
  bootstrap:
    initdb:
      database: bookorbit
      owner: bookorbit
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_trgm
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
        - CREATE EXTENSION IF NOT EXISTS vector
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  storage:
    size: 4Gi
    storageClass: longhorn-cnpg
