---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: app-template
    namespace: anubis
    releaseName: anubis
    repo: oci://ghcr.io/bjw-s-labs/helm
    valuesFile: ../../base/values.yaml
    version: 4.2.0
