---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: outline-postgres
spec:
  instances: 2
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: outline
      owner: outline
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  storage:
    size: 10Gi
    storageClass: longhorn-cnpg
