---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: outline-cnpg-main
spec:
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
