# https://github.com/trueforge-org/truecharts/blob/master/charts/stable/jellyfin/values.yaml
---
image:
  repository: oci.trueforge.org/containerforge/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.11.11@sha256:7f5325bd23b7445a8fda17b6d2d24033e3935536789f682aed63698b7b3a97c6
# -- enable Jellyfin autodiscovery on LAN
autodiscovery:
  enabled: true
