# https://github.com/trueforge-org/truecharts/blob/master/charts/stable/jellyfin/values.yaml
---
image:
  repository: oci.trueforge.org/containerforge/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.11.6@sha256:1a6f5fae6a460526045b33de8ff87581569ba512cd6872997a1856ac66396299
# -- enable Jellyfin autodiscovery on LAN
autodiscovery:
  enabled: true
