# https://github.com/trueforge-org/truecharts/blob/master/charts/stable/jellyfin/values.yaml
---
image:
  repository: oci.trueforge.org/containerforge/jellyfin
  pullPolicy: IfNotPresent
  tag: 10.11.6@sha256:965939518f4ed55585d97137c4ab9dd665724c7b67ee762d9f525a243aade103
# -- enable Jellyfin autodiscovery on LAN
autodiscovery:
  enabled: true
