---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Request management and media discovery for Jellyfin.
    gethomepage.dev/group: Media Requests
    gethomepage.dev/icon: overseerr.svg
    gethomepage.dev/name: Seerr
    gethomepage.dev/widget.type: "seerr"
    gethomepage.dev/widget.url: "http://seerr.seerr.svc.cluster.local:80"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SEERR_KEY}}"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: http-gateway-api
      namespace: envoy-gateway-ingress
  hostnames:
    - "get.${FQDN_01}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: seerr
          namespace: seerr
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
