locals {
  envcommon = "${get_parent_terragrunt_dir()}/_envcommon"

  # Automatically load account-level variables
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))

  # Automatically load node-level variables (may not exist for non-Proxmox stacks)
  node_vars = try(read_terragrunt_config(find_in_parent_folders("node.hcl")), { locals = {} })
}

# Base versions will be generated by specific provider configurations
# Proxmox units get versions.tf from proxmox-provider.hcl
# Non-Proxmox units should define their own required_providers

# ---------------------------------------------------------------------------------------------------------------------
# GLOBAL PARAMETERS
# These variables apply to all configurations in this subfolder. These are automatically merged into the child
# `terragrunt.hcl` config via the include block.
# ---------------------------------------------------------------------------------------------------------------------

# Configure root level variables that all resources can inherit. This is especially helpful with multi-account configs
# where terraform_remote_state data sources are placed directly into the modules.
inputs = merge(
  local.account_vars.locals,
  local.node_vars.locals,
)
