locals {
  envcommon = "${get_parent_terragrunt_dir()}/_envcommon"

  # Automatically load account-level variables
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))

  # Automatically load node-level variables (may not exist for non-Proxmox stacks)
  node_vars = try(read_terragrunt_config(find_in_parent_folders("node.hcl")), { locals = {} })
}


# Generating remote state settings with Terragrunt:
# https://terragrunt.gruntwork.io/docs/features/state-backend/#generating-remote-state-settings-with-terragrunt
generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite_terragrunt"
  # Define R2 backend:
  # https://developers.cloudflare.com/terraform/advanced-topics/remote-backend/#define-r2-backend
  contents = <<EOF
terraform {
  backend "s3" {
    bucket = "${local.account_vars.locals.cloudflare.bucket_name}"
    key    = "terragrunt/infrastructure-live/${path_relative_to_include()}/tofu.tfstate"
    region = "auto"

    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true

    encrypt      = true
    use_lockfile = true

    endpoints = { s3 = "${local.account_vars.locals.cloudflare.r2_endpoint}" }
  }
}
EOF
}

# Base versions will be generated by specific provider configurations
# Proxmox units get versions.tf from proxmox-provider.hcl
# Non-Proxmox units should define their own required_providers

# ---------------------------------------------------------------------------------------------------------------------
# GLOBAL PARAMETERS
# These variables apply to all configurations in this subfolder. These are automatically merged into the child
# `terragrunt.hcl` config via the include block.
# ---------------------------------------------------------------------------------------------------------------------

# Configure root level variables that all resources can inherit. This is especially helpful with multi-account configs
# where terraform_remote_state data sources are placed directly into the modules.
inputs = merge(
  local.account_vars.locals,
  local.node_vars.locals,
)
