---
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "${FQDN_01},*.${FQDN_01}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      targetPort: 15021
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http3
      port: 443
      targetPort: 443
      protocol: UDP
autoscaling:
  enabled: false
replicaCount: 3
labels:
  "istio": ingressgateway
  # By default, don't enroll gateways into the ambient dataplane
  "istio.io/dataplane-mode": none
