---
# Run with: `docker compose run --user "$(id -u):$(id -g)" --rm runner`
services:
  runner:
    image: homelab-as-code-runner
    container_name: homelab-as-code-runner
    network_mode: host
    volumes:
      - "../homelab-as-code:/homelab-as-code:rw"
      - "${HOME}/.kube/config:/home/runner/.kube/config:rw"
      - "${HOME}/.talos/config:/home/runner/.talos/config:rw"
    user: "${UID:-1000}:${GID:-1000}"
