---
# Run with: `docker compose run --user "$(id -u):$(id -g)" --rm runner`
services:
  runner:
    image: homelab-as-code-runner
    container_name: homelab-as-code-runner
    network_mode: host
    volumes:
      # path is relative to the compose file’s directory
      - "../homelab-as-code:/homelab-as-code"
      - "${HOME}/.kube/config:/home/runner/.kube/config"
    user: "${UID:-1000}:${GID:-1000}"
