---
secrets:
  karakeep:
    enabled: false
  meilesearch: # Typo in upstream chart, keep this misspelling because this is the correct key for the chart
    enabled: false
applicationProtocol: https
applicationHost: "links.${FQDN_01}"
controllers:
  karakeep:
    containers:
      karakeep:
        env:
          DISABLE_SIGNUPS: true
          DISABLE_PASSWORD_AUTH: true
          OAUTH_AUTO_REDIRECT: true
          OAUTH_PROVIDER_NAME: "Kanidm"
          OAUTH_CLIENT_ID:
            valueFrom:
              secretKeyRef:
                name: karakeep-kanidm-oauth2-credentials
                key: CLIENT_ID
          OAUTH_CLIENT_SECRET:
            valueFrom:
              secretKeyRef:
                name: karakeep-kanidm-oauth2-credentials
                key: CLIENT_SECRET
          OAUTH_WELLKNOWN_URL: "https://auth.${FQDN_01}/oauth2/openid/$(OAUTH_CLIENT_ID)/.well-known/openid-configuration"
        envFrom:
          - secretRef:
              name: "karakeep-secrets"
    pod:
      annotations:
        secret.reloader.stakater.com/reload: "karakeep-kanidm-oauth2-credentials,karakeep-secrets"
meilisearch:
  auth:
    existingMasterKeySecret: "karakeep-secrets"
  podAnnotations:
    secret.reloader.stakater.com/reload: "karakeep-secrets"
