---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: homepage
    repo: oci://oci.trueforge.org/truecharts
    version: 11.18.6
    releaseName: homepage
    namespace: homepage
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
configMapGenerator:
  - name: env-vars
    envs:
      - /tmp/env-vars.env
replacements:
  - path: replacements.yaml
