---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_02"
  targets:
    - select:
        kind: Deployment
        name: homepage
      fieldPaths:
        - spec.template.spec.containers.[name=homepage].env.[name=HOMEPAGE_ALLOWED_HOSTS].value
      options:
        delimiter: "."
        index: 1
