---
# homepage-values.yaml
global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
ingress:
  main:
    enabled: true
    ingressClassName: tailscale
    hosts:
      - host: homepage
        paths:
          - path: "/"
            pathType: Prefix
    # drop this block if you don’t have cert-manager
    tls:
      - hosts:
          - homepage
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            # Set this to your host (example: home.mydomain.com)
            HOMEPAGE_ALLOWED_HOSTS: "home.${FQDN_02}"
