---
# homepage-values.yaml
global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
ingress:
  main:
    enabled: true
    ingressClassName: tailscale
    hosts:
      - host: "home.${FQDN_02}"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - "home.${FQDN_02}"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEPAGE_ALLOWED_HOSTS: "home.${FQDN_02}"
