---
- when: ansible_facts["distribution"] == 'Debian' or ansible_facts["distribution"] == 'Ubuntu'
  block:
    - ansible.builtin.include_tasks:
        file: deb/apt-upgrade.yml
- when: ansible_facts["distribution"] == 'Fedora' and ansible_facts["cmdline"].ostree is not defined
  block:
    - ansible.builtin.include_tasks:
        file: rpm/dnf-upgrade.yml
- ansible.builtin.include_tasks:
    file: package/package.yml
