---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.PRIVATE_REPO_01"
  targets:
    - select:
        kind: ApplicationSet
      fieldPaths:
        - spec.generators.0.git.repoURL
        - spec.template.spec.source.repoURL
