---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: radarr
    repo: oci://oci.trueforge.org/truecharts
    version: 27.2.2
    releaseName: radarr-uhd
    namespace: servarr
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars-radarr-uhd
    envs:
      - /tmp/env-vars.env
replacements:
  - path: replacements.yaml
