---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: karakeep
  namespace: karakeep
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          kopiur.home-operations.com/policy: karakeep
      spec:
        accessModes:
          - ReadWriteOnce
        dataSourceRef:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: kopiur-restore
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem
