---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/cnpg-cluster.yaml
  - resources/httproute.yaml
helmCharts:
  - name: mealie
    repo: oci://oci.trueforge.org/truecharts
    version: 27.8.0
    releaseName: mealie
    namespace: mealie
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars
    envs:
      - /tmp/env-vars.env
  - name: mealie-oidc
    literals:
      - AUTH_HOST=auth.${FQDN_01}
    options:
      disableNameSuffixHash: true
replacements:
  - path: replacements.yaml
