---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grimmory
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Self-hosted book library manager.
    gethomepage.dev/group: Media
    gethomepage.dev/icon: sh-grimmory.svg
    gethomepage.dev/name: Grimmory
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance=grimmory"
    gethomepage.dev/widget.type: "booklore"
    gethomepage.dev/widget.url: "http://grimmory.grimmory.svc.cluster.local:6060"
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_GRIMMORY_USERNAME}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_GRIMMORY_PASSWORD}}"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: http-gateway-api
      namespace: envoy-gateway-ingress
  hostnames:
    - "grimmory.${FQDN_01}"
  rules:
    - filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: grimmory.${FQDN_01}
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Port
                value: "443"
      backendRefs:
        - group: ""
          kind: Service
          name: grimmory
          namespace: grimmory
          port: &port 6060
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grimmory-redirect
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: http-gateway-api
      namespace: envoy-gateway-ingress
  hostnames:
    - "books.${FQDN_01}"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: "grimmory.${FQDN_01}"
            statusCode: 308
      matches:
        - path:
            type: PathPrefix
            value: /
