---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    # HTTPRoute hostname
    - select:
        kind: HTTPRoute
        name: streamystats
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
    # KanidmOAuth2Client landing (origin) and redirect URLs
    - select:
        kind: KanidmOAuth2Client
        name: streamystats
      fieldPaths:
        - spec.origin
        - spec.redirectUrl.0
      options:
        delimiter: "."
        index: 1
