---
controllers:
  frontend:
    pod:
      annotations:
        secret.reloader.stakater.com/reload: "streamystats-postgres-app,streamystats-secrets"
    containers:
      main:
        env:
          DATABASE_URL:
            secretKeyRef:
              name: streamystats-postgres-app
              key: uri
        envFrom:
          - secretRef:
              name: streamystats-secrets
  job-server:
    pod:
      annotations:
        secret.reloader.stakater.com/reload: "streamystats-postgres-app"
    containers:
      main:
        env:
          DATABASE_URL:
            secretKeyRef:
              name: streamystats-postgres-app
              key: uri
