apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: 9.1.13
    releaseName: reflector
    namespace: kube-system
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
