---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: default-system-backup
  namespace: longhorn-system
spec:
  name: default-system-backup
  task: system-backup
  cron: "0 4 * * *"
  retain: 7
  concurrency: 1
  labels: {}
  parameters:
    volume-backup-policy: if-not-present
  groups: []
