---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-daily-backup.yaml
  # - default-monthly-backup.yaml
  - default-system-backup.yaml
  # - default-weekly-backup.yaml
