---
- name: Create role 'Terraforming' with specific privileges
  ansible.builtin.command:
    cmd: >-
      pveum role add Terraforming -privs
      "Realm.AllocateUser, VM.PowerMgmt, VM.GuestAgent.Unrestricted, Sys.Console, Sys.Audit,
      Sys.AccessNetwork, VM.Config.Cloudinit, VM.Replicate, Pool.Allocate, SDN.Audit, Realm.Allocate,
      SDN.Use, Mapping.Modify, VM.Config.Memory, VM.GuestAgent.FileSystemMgmt, VM.Allocate, SDN.Allocate,
      VM.Console, VM.Clone, VM.Backup, Datastore.AllocateTemplate, VM.Snapshot, VM.Config.Network, Sys.Incoming,
      Sys.Modify, VM.Snapshot.Rollback, VM.Config.Disk, Datastore.Allocate, VM.Config.CPU, VM.Config.CDROM, Group.Allocate,
      Datastore.Audit, VM.Migrate, VM.GuestAgent.FileWrite, Mapping.Use, Datastore.AllocateSpace, Sys.Syslog, VM.Config.Options,
      Pool.Audit, User.Modify, VM.Config.HWType, VM.Audit, Sys.PowerMgmt, VM.GuestAgent.Audit, Mapping.Audit, VM.GuestAgent.FileRead,
      Permissions.Modify"
  register: role_add_result
  failed_when: role_add_result.rc != 0 and 'already exists' not in role_add_result.stderr
  changed_when: "'already exists' not in role_add_result.stderr"
- name: Check if role 'Terraforming' is already assigned to 'terraformer@pve'
  ansible.builtin.command: "pveum acl list"
  register: current_acls
  changed_when: false
- name: Assign role 'Terraforming' to user 'terraformer@pve' on root '/'
  ansible.builtin.command:
    cmd: "pveum aclmod / -user terraformer@pve -role Terraforming"
  when: "'/    │ Terraforming │ user │ terraformer@pve' not in current_acls.stdout"
  register: aclmod_result
  failed_when: aclmod_result.rc != 0
  changed_when: true
