---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: pve
      vars:
        ansible_connection: ssh
        ansible_port: 22
        ansible_ssh_common_args: -o StrictHostKeyChecking=no
