---
roles:
  # https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/docker/
  - name: geerlingguy.docker
    version: ">=7.4.7"
    source: https://galaxy.ansible.com
collections:
  # https://galaxy.ansible.com/ui/repo/published/community/general/
  - name: community.general
    version: ">=10.7.0"
    source: https://galaxy.ansible.com
