---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: streamystats-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie
  storage:
    size: 5Gi
    storageClass: longhorn-cnpg
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
  bootstrap:
    initdb:
      database: streamystats
      owner: streamystats
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: streamystats-database
spec:
  name: streamystats
  owner: streamystats
  cluster:
    name: streamystats-postgres
  extensions:
    - ensure: present
      name: vector
    - ensure: present
      name: vchord
      version: 1.1.1
