---
apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "${FQDN_01},*.${FQDN_01}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    gateway.envoyproxy.io/owning-gateway-name: http-gateway-api
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-ingress
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 10080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 10443
