---
deschedulingInterval: 5m
kind: Deployment
leaderElection:
  enabled: true
replicas: 2
service:
  enabled: true
serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
