---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    # HTTPRoute hostname
    - select:
        kind: HTTPRoute
        name: it-tools
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
    - select:
        kind: ConfigMap
        name: it-tools-oidc
      fieldPaths:
        - data.AUTH_HOST
        - data.it-tools_HOST
      options:
        delimiter: "."
        index: 1

- source:
    kind: ConfigMap
    name: it-tools-oidc
    fieldPath: "data.AUTH_HOST"
  targets:
    - select:
        kind: RequestAuthentication
        name: it-tools-kanidm
      fieldPaths:
        - spec.jwtRules.0.issuer
      options:
        delimiter: "/"
        index: 2

- source:
    kind: ConfigMap
    name: it-tools-oidc
    fieldPath: "data.it-tools_HOST"
  targets:
    - select:
        kind: AuthorizationPolicy
        name: it-tools-authservice
      fieldPaths:
        - spec.rules.0.to.0.operation.hosts.0
    - select:
        kind: AuthorizationPolicy
        name: it-tools-deny-non-members
      fieldPaths:
        - spec.rules.0.to.0.operation.hosts.0
