---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/pvc-smb-mediadata-rwx.yaml
components:
  - ../../../../../../components/kopiur-volume
helmCharts:
  - name: qbittorrent
    repo: oci://oci.trueforge.org/truecharts
    version: 25.11.0
    releaseName: qbittorrent
    namespace: qbittorrent
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars
    envs:
      - /tmp/env-vars.env
replacements:
  - path: replacements.yaml
patches:
  - target:
      kind: SnapshotPolicy
      name: kopiur-snapshot-policy
    patch: |-
      - op: replace
        path: /spec/sources/0/pvcSelector/labelSelector/matchLabels/kopiur.home-operations.com~1policy
        value: qbittorrent
  - target:
      kind: PersistentVolumeClaim
      name: qbittorrent-config
    patch: |-
      - op: add
        path: /metadata/labels/kopiur.home-operations.com~1policy
        value: qbittorrent
      - op: add
        path: /spec/dataSourceRef
        value:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: kopiur-restore
