---
global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
ingress:
  main:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: ingress-proxies
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: BitTorrent client.
      gethomepage.dev/group: Downloads
      gethomepage.dev/icon: qbittorrent.svg
      gethomepage.dev/name: qBittorrent
      gethomepage.dev/pod-selector: "app.kubernetes.io/instance=qbittorrent"
      gethomepage.dev/widget.type: "qbittorrent"
      gethomepage.dev/widget.url: "http://qbittorrent.qbittorrent.svc.cluster.local:10095"
    hosts:
      - host: "qbit.${FQDN_02}"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - "qbit.${FQDN_02}"
persistence:
  config:
    enabled: true
    mountPath: "/config"
  mediadata:
    enabled: true
    type: pvc
    mountPath: "/MediaData"
    readOnly: false
    existingClaim: smb-mediadata-rwx
