---
webhook:
  ## Enable validating webhook for KanidmGroup
  enabled: true

  ## Use cert-manager to manage webhook TLS certificates
  certManager:
    enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
  dashboards:
    enabled: true
