---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeroclaw
  annotations:
    gethomepage.dev/description: Personal AI assistant.
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: AI
    gethomepage.dev/icon: https://raw.githubusercontent.com/zeroclaw-labs/zeroclaw/master/apps/tauri/icons/icon.png
    gethomepage.dev/name: ZeroClaw
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance=zeroclaw"
    tailscale.com/proxy-group: ingress-proxies
spec:
  ingressClassName: tailscale
  rules:
    - host: "zeroclaw.${FQDN_02}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zeroclaw
                port:
                  name: gateway
  tls:
    - hosts:
        - "zeroclaw.${FQDN_02}"
