---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes-agent
resources:
  - ../../base
  - external-secrets
  - resources/hermes-instance.yaml
  - resources/ingress.yaml
configMapGenerator:
  - name: env-vars-hermes-agent
    envs:
      - /tmp/env-vars.env
    literals:
      - OIDC_ISSUER_PATH=oauth2/openid/hermes
replacements:
  - path: replacements.yaml
