---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 2
  storage:
    size: 1Gi
    storageClass: longhorn-cnpg
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.0-0.5.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  nodeSelector:
    storage-nonrotationaldisk: "true"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-database-immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-database
  extensions:
    - name: vector
    - name: cube
    - name: vchord
    - name: earthdistance
