---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-dns-target-ddns
  namespace: envoy-gateway-ingress
rules:
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - envoy-gateway-ingress
    verbs:
      - get
      - patch
