---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zeroclaw-auth-codex.yaml.externalsecret
  - zeroclaw-calendar-mcp.yaml.externalsecret
  - zeroclaw-garmin-mcp.yaml.externalsecret
  - zeroclaw-groq-api-key.yaml.externalsecret
  - zeroclaw-ha-mcp.yaml.externalsecret
  - zeroclaw-secret-key.yaml.externalsecret
  - zeroclaw-servarr-secrets.yaml.externalsecret
  - zeroclaw-tandoor-mcp.yaml.externalsecret
  - zeroclaw-trek-mcp.yaml.externalsecret
  - zeroclaw-telegram-arr-bot.yaml.externalsecret
  - zeroclaw-telegram-chef-bot.yaml.externalsecret
  - zeroclaw-telegram-coach-bot.yaml.externalsecret
  - zeroclaw-telegram-default-bot.yaml.externalsecret
  - zeroclaw-telegram-household-bot.yaml.externalsecret
  - zeroclaw-telegram-media-1-bot.yaml.externalsecret
  - zeroclaw-telegram-media-2-bot.yaml.externalsecret
  - zeroclaw-telegram-smart-homer-bot.yaml.externalsecret
  - zeroclaw-telegram-travel-agent-bot.yaml.externalsecret
  - zeroclaw-yuvomi-mcp.yaml.externalsecret
