---
controllers:
  chrome:
    containers:
      chrome:
        image:
          repository: ghcr.io/karakeep-app/karakeep-chrome
          tag: 151.0.7922.47-r1@sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7
        args:
          - --disable-blink-features=AutomationControlled
          - --disable-dev-shm-usage
          - --disable-gpu
          - --hide-scrollbars
          - --window-size=1440,900
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
  karakeep:
    containers:
      karakeep:
        env:
          DB_WAL_MODE: true
          S6_READ_ONLY_ROOT: 1
          S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/health
                port: 3000
              periodSeconds: 5
              timeoutSeconds: 5
              failureThreshold: 30
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/health
                port: 3000
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/health
                port: 3000
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
defaultPodOptions:
  hostUsers: false
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault
ingress:
  karakeep:
    enabled: false
persistence:
  run:
    type: emptyDir
    advancedMounts:
      karakeep:
        karakeep:
          - path: /run
  karakeep-tmp:
    type: emptyDir
    advancedMounts:
      karakeep:
        karakeep:
          - path: /tmp
            readonly: false
