---
# renovate: datasource=github-releases depName=immich-app/immich
immichVersion: v3.0.2

controllers:
  main:
    containers:
      main:
        image:
          repository: &immichServerRepository ghcr.io/immich-app/immich-server
          tag: '{{ .Values.immichVersion }}'

server:
  controllers:
    main:
      containers:
        main:
          image:
            repository: *immichServerRepository
            tag: '{{ .Values.immichVersion }}'
    microservices:
      containers:
        main:
          image:
            repository: *immichServerRepository
            tag: '{{ .Values.immichVersion }}'

machine-learning:
  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: '{{ .Values.immichVersion }}-openvino'

valkey:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/valkey-io/valkey

immich:
  metrics:
    enabled: true
