---
- source:
    kind: ConfigMap
    name: env-vars-bazarr-uhd
    fieldPath: "data.FQDN_02"
  targets:
    # Ingress
    - select:
        kind: Ingress
        name: bazarr-uhd
      fieldPaths:
        - spec.rules.0.host
        - spec.tls.0.hosts.0
      options:
        delimiter: "."
        index: 1
