---
image:
  registry: ghcr.io
  repository: seerr-team/seerr
  pullPolicy: IfNotPresent
  tag: 'preview-new-oidc'
  sha: 'deb28ef85800e3de28f9b96965127cdd6d5a2408df3545cddb6f6c37fc479a81'
nameOverride: 'seerr'
