---
image:
  registry: ghcr.io
  repository: v3djg6gl/seerr
  pullPolicy: IfNotPresent
  tag: 'feat-oidc-jellyfin-quickconnect'
  sha: 'd2b09093792b8970a2f3d9c723dda7339f69706565f2bb896c2d3440148411c0'
nameOverride: 'seerr'
