---
image:
  registry: ghcr.io
  repository: seerr-team/seerr
  pullPolicy: IfNotPresent
  tag: 'preview-new-oidc'
  sha: '4957b2eb2599d90ca84b03ec2afb694d8608a7ca34d72166037a3d2c8a485c16'
nameOverride: 'seerr'
