---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: cilium
    repo: oci://quay.io/cilium/charts
    version: 1.18.6
    releaseName: cilium
    namespace: kube-system
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
