---
defaultSettings:
  defaultDataLocality: best-effort
  defaultDataPath: "/var/mnt/longhorn"
  defaultReplicaCount: '{"v1":"2","v2":"2"}'
  nodeDrainPolicy: block-for-eviction-if-contains-last-replica
  detachManuallyAttachedVolumesWhenCordoned: true
  storageOverProvisioningPercentage: 1000
persistence:
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
preUpgradeChecker:
  # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
  jobEnabled: false
image:
  longhorn:
    instanceManager:
      repository: longhornio/longhorn-instance-manager
      tag: v1.11.0-hotfix-1
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
