---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    - select:
        kind: HTTPRoute
        name: grimmory
      fieldPaths:
        - spec.hostnames.0
        - spec.rules.0.filters.0.requestHeaderModifier.set.0.value
      options:
        delimiter: "."
        index: 1
    - select:
        kind: HTTPRoute
        name: grimmory-redirect
      fieldPaths:
        - spec.hostnames.0
        - spec.rules.0.filters.0.requestRedirect.hostname
      options:
        delimiter: "."
        index: 1
