---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: csi-driver-smb
    namespace: kube-system
    releaseName: csi-driver-smb
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    valuesFile: ../../base/values.yaml
    version: 1.18.0
