---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes-operator
resources:
  - ../../base
helmCharts:
  - name: hermes-operator
    repo: oci://ghcr.io/paperclipinc/charts
    version: 0.1.18
    releaseName: hermes-operator
    namespace: hermes-operator
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
