---
- name: Bootstrap nodes over LAN, install Tailscale, then swap to overlay
  hosts: pve
  become: true
  gather_facts: true
  tasks:
    - ansible.builtin.include_role:
        name: tailscale-bootstrap
        apply:
          tags: tailscale-bootstrap
      vars:
        inventory_to_overwrite: "{{ hostvars[inventory_hostname].inventory_file }}"
        current_user: "{{ lookup('env','USER') }}"
      tags: tailscale-bootstrap
    - name: Setup PVE cluster
      tags: proxmox
      block:
        - name: Ensure "/var/lib/pve/local-btrfs" directory exists (with 755 permissions and root ownership)
          ansible.builtin.file:
            path: "{{ pve_storages | selectattr('name', 'equalto', 'local-btrfs') | map(attribute='path') | first }}"
            state: directory
            owner: root
            group: root
            mode: '0755'
        - ansible.builtin.include_role:
            name: lae.proxmox
            apply:
              become: true
    - ansible.builtin.include_role:
        name: cert
        apply:
          tags: cert
      tags: cert
      vars:
        renew_before_expiry_days: 7  # renew when the cert expires in N days or less
        force_renew_cert: false
    - name: Create Proxmox users, roles and tokens
      ansible.builtin.include_role:
        name: proxmox-permissions
        apply:
          tags: proxmox-permissions
      tags: proxmox-permissions
    - name: Install other packages
      ansible.builtin.include_role:
        name: install-packages
        apply:
          tags: install-packages
      tags: install-packages
    - name: Disable PVE subscription nag
      ansible.builtin.include_role:
        name: pve-remove-nag
        apply:
          tags: pve-remove-nag
      tags: pve-remove-nag
