---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: krr
  namespace: krr
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - args: [--history_duration, "336", --max-workers, "3", --prometheus-url, "http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8428", --width, "2048"]
              command: [python, krr.py, simple]
              env:
                - name: FORCE_COLOR
                  value: "1"
              image: robustadev/krr:v1.30.0@sha256:b8d782e568c7d23aac6460e69dd136e44eca67e8cbfce19915197a48dc28e23f
              imagePullPolicy: IfNotPresent
              name: krr
              resources:
                limits:
                  memory: 1Gi
                requests:
                  cpu: 200m
                  memory: 512Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
          enableServiceLinks: false
          restartPolicy: Never
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: krr
      ttlSecondsAfterFinished: 604800  # 7 days
  schedule: "0 4 * * 0"
  successfulJobsHistoryLimit: 1
  timeZone: Asia/Jerusalem
