---
blocky:
  enablePrometheus: false
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 4000
        protocol: http
        targetPort: 4000
  dns:
    enabled: true
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "192.168.1.53"
    ports:
      dns:
        enabled: true
        protocol: udp
        port: 53
        targetPort: 53
      dnstcp:
        enabled: true
        protocol: tcp
        port: "{{ .Values.service.dns.ports.dns.port }}"
        targetPort: 53
  dot:
    enabled: true
    ports:
      dot:
        enabled: true
        port: 853
        protocol: tcp
        targetPort: 853
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 4443
        protocol: https
        targetPort: 4443
  k8sgateway:
    enabled: true
    ports:
      k8sgateway:
        enabled: true
        port: 5353
        protocol: udp
        targetPort: 5353
logTimestamp: true
logPrivacy: true
minTlsServeVersion: 1.3
defaultUpstreams:
  # Cloudflare DoH
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-querys
bootstrapDns:
  upstream: "1.1.1.1"
k8sgateway:
  enabled: true
  # -- TTL for non-apex responses (in seconds)
  ttl: 300
  # -- Limit what kind of resources to watch, e.g. watchedResources: [ Ingress | Service | HTTPRoute | TLSRoute | GRPCRoute | DNSEndpoint ]
  watchedResources:
    - Ingress
    - Service
    - HTTPRoute
  # -- Service name of a secondary DNS server (should be `serviceName.namespace`)
  secondary: ""
  # -- Override the default `serviceName.namespace` domain apex
  apex: ""
  # -- list of processed domains
  domains: []
  # -- Delegated domain
  # - domain: "example.com"
  #   # -- Optional configuration option for DNS01 challenge that will redirect all acme
  #   # challenge requests to external cloud domain (e.g. managed by cert-manager)
  #   # See: https://cert-manager.io/docs/configuration/acme/dns01/
  #   dnsChallenge:
  #     enabled: false
  #     domain: dns01.clouddns.com
  forward:
    enabled: false
    primary: tls://1.1.1.1
    secondary: tls://1.0.0.1
    options:
      - name: tls_servername
        value: cloudflare-dns.com
configmap:
  dashboard:
    enabled: false
  datasource:
    enabled: false
metrics:
  main:
    enabled: false
redis:
  enabled: true
queryLog:
  type: null
cnpg:
  main:
    enabled: false
