---
cluster_secret_store_name: bitwarden-secretsmanager
# Bitwarden service endpoints
api_url: "https://api.bitwarden.com."
identity_url: "https://identity.bitwarden.com."
bitwarden_sdk_server_url: "https://bitwarden-sdk-server.{{ namespace }}.svc.cluster.local:9998"
# IDs
organization_id: ""
project_id: ""
# Kubernetes object details
namespace: bitwarden
token_secret_name: bitwarden-access-token
token_key: token
ca_secret_name: bitwarden-tls-certs
ca_key: ca.crt

# Optional: pass a custom kubeconfig; omit to use in-cluster config
# kubeconfig_path: "/home/ansible/.kube/config"
