---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secrets/github-app-secret.yaml.externalsecret
  - resources/namespace.yaml
  - resources/serviceaccount.yaml
  - resources/role.yaml
  - resources/rolebinding.yaml
helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.0
    releaseName: arc-runner-set
    namespace: arc-runners
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
