---
# Set to your GitHub repo, org, or enterprise URL
githubConfigUrl: "https://github.com/roib20"

# References the secret created by the ExternalSecret
githubConfigSecret: github-app-secret

minRunners: 0
maxRunners: 5

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-systems

containerMode:
  type: "dind"
