---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
configMapGenerator:
  - name: zeroclaw-config
    files:
      - config.toml=files/config.toml
    options:
      disableNameSuffixHash: true
