# Basic configuration - see examples/oauth2.yaml for all options
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: forgejo
  namespace: forgejo
spec:
  kanidmRef:
    name: idm
    namespace: kaniop
  displayname: Forgejo
  origin: "https://git.${FQDN_01}"
  redirectUrl:
    - "https://git.${FQDN_01}/user/oauth2/kanidm/callback"
  scopeMap:
    - group: idm_all_accounts
      scopes:
        - openid
        - email
        - profile
        - groups
        - forgejo
