---
replicaCount: 1

config:
  log-level: warn
  log-output: stdout
  metrics.enabled: false
  index:
    type: meilisearch

statefulSet:
  enabled: true

podSecurityContext:
  runAsUser: 0
  runAsGroup: 1000
  runAsNonRoot: false
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - DAC_OVERRIDE

resources:
  requests:
    cpu: 100m
    memory: 52M
  limits:
    memory: 256M

livenessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

persistence:
  enabled: true
  mode: shared
  existingClaim: ""
  create:
    enabled: true
    nameSuffix: shared
    storageClass: longhorn
    size: 2Gi
    accessModes:
      - ReadWriteMany
    annotations:
      helm.sh/resource-policy: keep

deployment:
  env:
    - name: UID
      value: "1000"
    - name: GID
      value: "1000"

ingress:
  enabled: false

service:
  ssh:
    enabled: true

meilisearch:
  enabled: true
  environment:
    MEILI_ENV: development

postgresql:
  enabled: false
