---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: renovate-operator
    repo: oci://ghcr.io/mogenius/helm-charts
    version: 4.3.2
    releaseName: renovate-operator
    namespace: renovate
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars
    envs:
      - /tmp/env-vars.env
  - name: renovate-operator-oidc
    literals:
      - OIDC_ISSUER_HOST=auth.${FQDN_01}
      - OIDC_REDIRECT_HOST=renovate.${FQDN_02}
    options:
      disableNameSuffixHash: true
replacements:
  - path: replacements.yaml
patches:
  - path: patches/deployment-oidc-client-id-secretref.yaml
    target:
      kind: Deployment
      name: renovate-operator
