---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_02"
  targets:
    - select:
        kind: Ingress
      fieldPaths:
        - spec.rules.0.host
        - spec.tls.0.hosts.0
      options:
        delimiter: "."
        index: 1
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    - select:
        group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: renovate-operator-webhook
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
