---
ingress:
  enabled: true
  ingressClassName: tailscale
  host: "renovate.${FQDN_02}"
  tls:
    - hosts:
        - "renovate.${FQDN_02}"
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Operator to streamline renovate executions in Kubernetes.
    gethomepage.dev/group: Operations
    gethomepage.dev/icon: renovate.svg
    gethomepage.dev/name: Renovate Operator
    gethomepage.dev/pod-selector: "app=renovate-operator"
webhook:
  enabled: true
  port: 8082
  route:
    enabled: true
    annotations: {}
    labels: {}
    hostnames:
      - "renovate.${FQDN_01}"
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: http-gateway-api
        namespace: istio-ingress
auth:
  oidc:
    enabled: true
    issuerUrl: "https://auth.${FQDN_01}/oauth2/openid/renovate-operator"
    clientId: ""
    existingSecret: renovate-operator-kanidm-oauth2-credentials
    secretKey: CLIENT_SECRET
    sessionSecretKey: CLIENT_SECRET
    redirectUrl: "https://renovate.${FQDN_02}/auth/callback"
    additionalScopes:
      - groups
  github:
    enabled: false
