---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]

tasks:
  setup-cluster:
    desc: Run Ansible VM playbook (prompts for ANSIBLE_PASS)
    dir: "ansible/pve-cluster"
    interactive: true
    env:
      VAR_NAME: ANSIBLE_PASS
      VAR_CMD: "ansible-playbook -i inventory.yml cluster-playbook.yml -k -K"
    cmds:
      - sh "{{.ROOT_DIR}}/.taskfiles/common/scripts/prompt.sh"
    preconditions:
      - test -f "{{.ANSIBLE_DIR}/pve-cluster/cluster-playbook.yml"
      - which ansible-playbook
