---
forceConfigFromValues: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              spec:
                timeoutSeconds: 15
            readiness:
              spec:
                timeoutSeconds: 15
configmap:
  config:
    data:
      bookmarks.yaml: |
        ---
      kubernetes.yaml: |
        ---
        # For configuration options and examples, please see:
        # https://gethomepage.dev/configs/kubernetes/

        mode: cluster
        ingress: true # default, enable ingress
        traefik: false # disable traefik ingressRoute
        gateway: true # enable gateway-api
      services.yaml: |
        ---
      settings.yaml: |
        ---
        providers:
          longhorn:
            url: http://longhorn-frontend.longhorn-system.svc.cluster.local
      widgets.yaml: |
        ---
        - kubernetes:
            cluster:
              # Shows the cluster node
              show: true
              # Shows the aggregate CPU stats
              cpu: true
              # Shows the aggregate memory stats
              memory: true
              # Shows a custom label
              showLabel: true
              label: "cluster"
            nodes:
              # Shows the cluster nodes
              show: true
              # Shows the CPU for each node
              cpu: true
              # Shows the memory for each node
              memory: true
              # Shows the label, which is always the node name
              showLabel: true
        - search:
            provider: google # google, duckduckgo, bing, baidu, brave or custom
            focus: false # Optional, will set focus to the search bar on page load
            showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
            target: _blank # One of _self, _blank, _parent or _top
        - longhorn:
            # Show the expanded
            expanded: true
            # Shows a node representing the aggregate values
            total: true
            # Shows the node names as labels
            labels: true
            # Show the nodes
            nodes: true
