---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: spegel
    namespace: kube-system
    releaseName: spegel
    repo: oci://ghcr.io/spegel-org/helm-charts
    valuesFile: ../../base/values.yaml
    version: 0.3.0
