---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: http-gateway-api
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyPDB:
        minAvailable: 1
      envoyService:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "${FQDN_01},*.${FQDN_01}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        externalTrafficPolicy: Cluster
        type: LoadBalancer
