---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: http-gateway-api
spec:
  backendTLS:
    minVersion: "1.3"
    maxVersion: "1.3"
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                secret.reloader.stakater.com/reload: "tls-wildcard"
      envoyPDB:
        minAvailable: 1
      envoyService:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "${FQDN_01},*.${FQDN_01}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        externalTrafficPolicy: Cluster
        type: LoadBalancer
