---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-mediadata-rox
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: smb-mediadata
  resources:
    requests:
      storage: 100Ti
