---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pvc-smb-mediadata-rox.yaml
  - resource-claim-template.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: jellyfin
helmCharts:
  - name: jellyfin
    repo: oci://oci.trueforge.org/truecharts
    version: 22.2.31
    releaseName: jellyfin
    namespace: jellyfin
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
