---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/httproute.yaml
  - resources/pvc-smb-mediadata-rox.yaml
  - resources/resource-claim-template.yaml
patches:
  - path: patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: jellyfin
helmCharts:
  - name: jellyfin
    repo: oci://oci.trueforge.org/truecharts
    version: 23.1.1
    releaseName: jellyfin
    namespace: jellyfin
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars
    envs:
      - /tmp/env-vars.env
replacements:
  - path: replacements.yaml
