---
global:
  fallbackDefaults:
    pvcRetain: true
    pvcSize: 10Gi
persistence:
  config:
    enabled: true
    mountPath: "/config"
    storageClass: longhorn
  data:
    enabled: true
    mountPath: "/data"
    storageClass: longhorn
  logs:
    enabled: true
    mountPath: "/logs"
    type: "emptyDir"
  cache:
    enabled: true
    mountPath: "/cache"
    type: "emptyDir"
  transcode:
    enabled: true
    mountPath: "/cache/transcodes"
    type: "emptyDir"
  media:
    enabled: true
    type: pvc
    mountPath: "/media"
    readOnly: true
    existingClaim: smb-mediadata-rox
    subPath: Media
workload:
  main:
    podSpec:
      containers:
        main:
          resources:
            limits:
              memory: 8Gi
