---
persistence:
  config:
    enabled: true
    mountPath: "/config"
    storageClass: longhorn
    size: 10Gi
  data:
    enabled: true
    mountPath: "/data"
    storageClass: longhorn
    size: 10Gi
  logs:
    enabled: true
    mountPath: "/logs"
    type: "emptyDir"
  cache:
    enabled: true
    mountPath: "/cache"
    type: "emptyDir"
  transcode:
    enabled: true
    mountPath: "/cache/transcodes"
    type: "emptyDir"
  media:
    enabled: true
    type: pvc
    mountPath: "/media"
    readOnly: true
    existingClaim: smb-mediadata-rox
    subPath: Media
