---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate-operator
spec:
  template:
    spec:
      containers:
        - name: renovate-operator
          env:
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: renovate-operator-kanidm-oauth2-credentials
                  key: CLIENT_ID
