---
webhook:
  certManager:
    # -- Whether to use cert-manager to manage webhook tls
    enabled: true
    # -- Issuer group (only relevant if enabled is true; if unset, the default cert-manager group is used)
    issuerGroup: ""
    # -- Issuer kind (only relevant if enabled is true; if unset, the default cert-manager type 'Issuer' is used)
    issuerKind: ""
    # -- Issuer name (only relevant if enabled is true; if unset, a self-signed issuer is used)
    issuerName: ""
metrics:
  podMonitor:
    # -- Whether to create a PodMonitor resource
    enabled: false
  prometheusRule:
    # -- Whether to create a PrometheusRule resource
    enabled: false
    # -- PrometheusRule rules
    rules: []
