---
apt_packages:
  # Proxmox packages
  - proxmox-default-kernel
  - proxmox-ve
  - postfix
  - open-iscsi
  - chrony
  - proxmox-kernel-7.0  # https://forum.proxmox.com/tags/opt-in-kernel/
  # Hardware packages
  - eject
  - firmware-sof-signed
  - mdadm
  # Other packages
  - guestfs-tools
  - lm-sensors
  - rsync
  - tmux
dnf_packages: []
