---
global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
podOptions:
  defaultAffinity: false
workload:
  main:
    podSpec:
      annotations:
        secret.reloader.stakater.com/reload: "servarr-postgres-app,servarr-secrets"
      containers:
        main:
          env:
            DYNACONF_analytics__enabled: false
            DYNACONF_auth__APIKEY:
              secretKeyRef:
                name: servarr-secrets
                key: bazarr_hd_api_key
                expandObjectName: false
            DYNACONF_auth__TYPE: "@null"
            DYNACONF_general__debug: false
            DYNACONF_general__instance_name: Bazarr HD
            DYNACONF_general__theme: auto
            DYNACONF_general__use_radarr: true
            DYNACONF_general__use_sonarr: true
            DYNACONF_radarr__apikey:
              secretKeyRef:
                name: servarr-secrets
                key: radarr_hd_api_key
                expandObjectName: false
            DYNACONF_radarr__ip: radarr-hd.servarr.svc.cluster.local
            DYNACONF_radarr__port: 7878
            DYNACONF_radarr__ssl: false
            DYNACONF_sonarr__apikey:
              secretKeyRef:
                name: servarr-secrets
                key: sonarr_hd_api_key
                expandObjectName: false
            DYNACONF_sonarr__ip: sonarr-hd.servarr.svc.cluster.local
            DYNACONF_sonarr__port: 8989
            DYNACONF_sonarr__ssl: false
            POSTGRES_ENABLED: true
            POSTGRES_HOST:
              secretKeyRef:
                name: servarr-postgres-app
                key: host
                expandObjectName: false
            POSTGRES_PORT:
              secretKeyRef:
                name: servarr-postgres-app
                key: port
                expandObjectName: false
            POSTGRES_USERNAME:
              secretKeyRef:
                name: servarr-postgres-app
                key: user
                expandObjectName: false
            POSTGRES_PASSWORD:
              secretKeyRef:
                name: servarr-postgres-app
                key: password
                expandObjectName: false
            POSTGRES_DATABASE: bazarr-hd
        exportarr:
          env:
            API_KEY:
              secretKeyRef:
                name: servarr-secrets
                key: bazarr_hd_api_key
                expandObjectName: false
ingress:
  main:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: ingress-proxies
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Bazarr HD is a companion application to Sonarr HD and Radarr HD that manages and downloads subtitles.
      gethomepage.dev/group: Servarr
      gethomepage.dev/icon: bazarr.svg
      gethomepage.dev/name: Bazarr HD
      gethomepage.dev/pod-selector: "app.kubernetes.io/instance=bazarr-hd"
      gethomepage.dev/widget.type: "bazarr"
      gethomepage.dev/widget.url: "http://bazarr-hd.servarr.svc.cluster.local:6767"
      gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_BAZARR_HD_KEY}}`}}"
    hosts:
      - host: "bazarr-hd.${FQDN_02}"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - "bazarr-hd.${FQDN_02}"
persistence:
  config:
    enabled: true
    mountPath: "/config"
    targetSelector:
      main:
        main:
          mountPath: /config
        exportarr:
          mountPath: /config
          readOnly: true
  mediadata:
    enabled: true
    type: pvc
    mountPath: "/MediaData"
    readOnly: false
    existingClaim: smb-mediadata-rwx
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: metrics
        path: /metrics
    targetSelector: metrics
    prometheusRule:
      enabled: true
