---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - smb-credentials.yaml.externalsecret
  - storageclass-mediadata.yaml
  # - pvc-mediadata-rox.yaml
  # - pvc-mediadata-rwx.yaml
  - storageclass-userdata.yaml
