---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/smb-credentials.yaml.externalsecret
  - resources/storageclass-mediadata.yaml
  # - resources/pvc-mediadata-rox.yaml
  # - resources/pvc-mediadata-rwx.yaml
