---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-mediadata
provisioner: smb.csi.k8s.io
parameters:
  source: "//truenas.local/MediaData"
  csi.storage.k8s.io/node-stage-secret-name: "smb-credentials"
  csi.storage.k8s.io/node-stage-secret-namespace: "smb"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=3000
  - gid=3000
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
