---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.10.1
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
patches:
  - target:
      kind: StorageClass
      name: longhorn
    patch: |-
      - op: add
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: "true"
