---
ingress:
  enabled: true
  ingressClassName: tailscale
  host: "longhorn.${FQDN_02}"
  tls: true
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Longhorn
    gethomepage.dev/description: Distributed block storage for Kubernetes.
    gethomepage.dev/group: Storage
    gethomepage.dev/icon: longhorn.svg
    gethomepage.dev/pod-selector: "app=longhorn-ui"
