---
ingress:
  enabled: true
  ingressClassName: tailscale
  host: "longhorn.${FQDN_02}"
  tls: true
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Longhorn
    gethomepage.dev/description: Distributed block storage for Kubernetes.
    gethomepage.dev/group: Storage
    gethomepage.dev/icon: longhorn.svg
    gethomepage.dev/widget.type: longhorn
    gethomepage.dev/widget.url: http://longhorn-frontend.longhorn-system.svc.cluster.local
