---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: external-secrets
    repo: oci://ghcr.io/external-secrets/charts
    version: 2.4.1
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
patches:
  - path: ../../base/patches/patch-namespace.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: bitwarden-sdk-server
  - path: ../../base/patches/patch-namespace.json
    target:
      group: ''
      version: v1
      kind: ServiceAccount
      name: bitwarden-sdk-server
  - path: ../../base/patches/patch-namespace.json
    target:
      group: ''
      version: v1
      kind: Service
      name: bitwarden-sdk-server
