---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    # HTTPRoute hostname
    - select:
        kind: HTTPRoute
        name: bookorbit
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
    # Public app URL
    - select:
        kind: Deployment
        name: bookorbit
      fieldPaths:
        - spec.template.spec.containers.[name=app].env.[name=CLIENT_URL].value
      options:
        delimiter: "."
        index: 1
