---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/intel/intel-resource-drivers-for-kubernetes/deployments/gpu/overlays/nfd_labeled_nodes?ref=gpu-v0.8.0
  - https://github.com/intel/intel-resource-drivers-for-kubernetes/deployments/gpu?ref=gpu-v0.8.0
