---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../../../components/kopiur-volume
  - ../../../../../../components/cnpg-backup
helmCharts:
  - name: immich
    repo: oci://ghcr.io/immich-app/immich-charts
    version: 0.13.2
    releaseName: immich
    namespace: immich
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
      - values-immich-config.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars-immich
    envs:
      - /tmp/env-vars.env
replacements:
  - path: replacements.yaml
patches:
  - target:
      kind: ObjectStore
      name: cnpg-backups
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: s3://k8s-backups/cnpg/immich
  - target:
      kind: ScheduledBackup
      name: cnpg-backup
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "0 0 22 * * *"
  - target:
      kind: SnapshotPolicy
      name: kopiur-snapshot-policy
    patch: |-
      - op: replace
        path: /spec/sources/0/pvcSelector/labelSelector/matchLabels/kopiur.home-operations.com~1policy
        value: immich
  - target:
      kind: PersistentVolumeClaim
      name: immich-server-profile
    patch: |-
      - op: add
        path: /metadata/labels/kopiur.home-operations.com~1policy
        value: immich
      - op: add
        path: /spec/dataSourceRef
        value:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: kopiur-restore
  - target:
      kind: PersistentVolumeClaim
      name: immich-server-thumbs
    patch: |-
      - op: add
        path: /metadata/labels/kopiur.home-operations.com~1policy
        value: immich
      - op: add
        path: /spec/dataSourceRef
        value:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: kopiur-restore
  - target:
      kind: PersistentVolumeClaim
      name: immich-valkey
    patch: |-
      - op: add
        path: /metadata/labels/kopiur.home-operations.com~1policy
        value: immich
      - op: add
        path: /spec/dataSourceRef
        value:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: kopiur-restore
