---
controllers:
  main:
    containers:
      main:
        image:
          # renovate: datasource=github-releases depName=immich-app/immich
          tag: v2.5.6
        env:
          - name: REDIS_HOSTNAME
            value: '{{ printf "%s-valkey" .Release.Name }}'
          - name: IMMICH_MACHINE_LEARNING_URL
            value: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: host
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: password
          - name: DB_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: dbname

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true

machine-learning:
  enabled: true
  controllers:
    main:
      containers:
        main:
          image:
            tag: release-openvino
