---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: cloudnative-pg
    repo: oci://ghcr.io/cloudnative-pg/charts
    version: 0.29.1
    releaseName: cloudnative-pg
    namespace: cnpg-system
    valuesFile: ../../base/values/cloudnative-pg-values.yaml
    additionalValuesFiles:
      - values/cloudnative-pg-values-override.yaml
    includeCRDs: true
  - name: plugin-barman-cloud
    repo: oci://ghcr.io/cloudnative-pg/charts
    version: 0.8.0
    releaseName: plugin-barman-cloud
    namespace: cnpg-system
    valuesFile: ../../base/values/plugin-barman-cloud-values.yaml
    additionalValuesFiles:
      - values/plugin-barman-cloud-values-override.yaml
    includeCRDs: true
