---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: tailscale-operator
    repo: oci://ghcr.io/home-operations/charts-mirror
    version: 1.88.4
    releaseName: tailscale-operator
    namespace: tailscale
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
