---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    "resources/core-networking/ingress-class.yaml",
    "resources/istio-networking/destination-rule.yaml",
    "resources/istio-networking/bridge-virtualservice.yaml",
    "resources/istio-networking/tls-gateway.yaml",
    "resources/gateway-api/http-gateway.yaml",
    "resources/istio-extensions/coraza-plugin.yaml",
  ],
}
