---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: sealed-secrets
    namespace: kube-system
    releaseName: sealed-secrets-controller
    repo: https://bitnami-labs.github.io/sealed-secrets
    valuesFile: ../../base/values.yaml
    version: 2.17.3
