---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: sealed-secrets
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 2.19.0
    releaseName: sealed-secrets
    namespace: kube-system
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
