---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/cilium-l2-lb.yaml
helmCharts:
  - name: blocky
    repo: oci://oci.trueforge.org/truecharts
    version: 22.4.0
    releaseName: blocky
    namespace: blocky
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
