---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: reflector
    repo: oci://ghcr.io/emberstack/helm-charts
    version: 10.0.18
    releaseName: reflector
    namespace: kube-system
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
