[tools]
"gh" = "latest"
"pipx:edge-tts" = "latest"
"ripgrep" = "latest"
"ubi:BtbN/FFmpeg-Builds" = { exe = "ffmpeg", matching = "lgpl.tar.xz", version = "latest" }
"ubi:linebender/resvg" = { exe = "resvg", matching = "resvg-linux", version = "latest" }
"uv" = "latest"
