---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: base
    namespace: istio-system
    releaseName: istio-base
    repo: oci://gcr.io/istio-release/charts
    valuesFile: ../../base/values.yaml
    version: 1.27.1
resources:
  - ../../base
