---
- when: ansible_facts["distribution"] == 'Debian' or ansible_facts["distribution"] == 'Ubuntu'
  block:
    - ansible.builtin.include_tasks:
        file: deb/apt-repos.yml
- name: Configure DNF settings for Fedora (non-OSTree)
  when: ansible_facts["distribution"] == 'Fedora' and ansible_facts["cmdline"].ostree is not defined
  block:
    - ansible.builtin.include_tasks:
        file: rpm/dnf-repos.yml
