---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-tls
  namespace: argocd
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-resources/tls-wildcard
type: kubernetes.io/tls
