---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: oci://ghcr.io/victoriametrics/helm-charts
    version: 0.85.7
    releaseName: victoria-metrics-k8s-stack
    namespace: monitoring
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: false
