---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secrets
  - resources/cnpg-cluster.yaml
  - resources/httproute.yaml
helmCharts:
  - name: outline
    repo: oci://oci.trueforge.org/truecharts
    version: 21.5.1
    releaseName: outline
    namespace: outline
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars-outline
    envs:
      - /tmp/env-vars.env
    literals:
      - OIDC_ISSUER_PATH=oauth2/openid/outline
replacements:
  - path: replacements.yaml
patches:
  - path: patches/remove-checksum-secrets-deployment.yaml
    target:
      kind: Deployment
      name: outline
