---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/httproute.yaml
patches:
  - path: patches/cnpg-affinity.yaml
    target:
      kind: Cluster
      name: outline-cnpg-main
helmCharts:
  - name: outline
    repo: oci://oci.trueforge.org/truecharts
    version: 20.0.0
    releaseName: outline
    namespace: outline
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars-outline
    envs:
      - /tmp/env-vars.env
    literals:
      - OIDC_ISSUER_PATH=oauth2/openid/outline
replacements:
  - path: replacements.yaml
