global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
cnpg:
  main:
    enabled: false
workload:
  main:
    podSpec:
      annotations:
        secret.reloader.stakater.com/reload: "outline-app-secrets,outline-kanidm-oauth2-credentials,outline-postgres-app,outline-rediscreds"
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: outline-postgres-app
                key: uri
                expandObjectName: false
