global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: false
    pvcSize: 1Gi
cnpg:
  main:
    enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: outline-postgres-app
                key: uri
                expandObjectName: false
