---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://k8s-backups@auto/longhorn"
  credentialSecret: "longhorn-backup-secret"
  pollInterval: 5m0s
