---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-servarr-postgres.yaml
  - database-bazarr-hd.yaml
  - database-bazarr-uhd.yaml
  - database-prowlarr.yaml
  - database-radarr-hd.yaml
  - database-radarr-uhd.yaml
  - database-sonarr-hd.yaml
  - database-sonarr-uhd.yaml
