---
- name: Add Debian repositories
  when: ansible_os_family == 'Debian'
  become: true
  block:
    - ansible.builtin.file:
        path: "/etc/apt/sources.list"
        state: file
        mode: "0644"
        owner: "root"
        group: "root"
        state: absent

    - ansible.builtin.deb822_repository:
        name: debian
        state: present
        types: [deb]
        uris: "http://deb.debian.org/debian"
        suites: ["{{ ansible_distribution_release|lower }}", "{{ ansible_distribution_release|lower }}-updates", "{{ ansible_distribution_release|lower }}-backports"]
        components: [main, contrib, non-free, non-free-firmware]
        signed_by: "/usr/share/keyrings/debian-archive-keyring.gpg"
        enabled: yes
  
    - ansible.builtin.deb822_repository:
        name: debian-security
        state: present
        types: [deb]
        uris: "http://deb.debian.org/debian-security"
        suites: ["{{ ansible_distribution_release|lower }}-security"]
        components: [main, contrib, non-free, non-free-firmware]
        signed_by: "/usr/share/keyrings/debian-archive-keyring.gpg"
        enabled: yes

- name: Add Proxmox repositories
  when: ansible_os_family == 'Debian'
  become: true
  block:
    - name: Proxmox SecureApt # https://pve.proxmox.com/wiki/Package_Repositories#repos_secure_apt
      ansible.builtin.get_url:
        url: "https://enterprise.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release|lower }}.gpg"
        dest: "/etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release|lower }}.gpg"
        checksum: sha512:7da6fe34168adc6e479327ba517796d4702fa2f8b4f0a9833f5ea6e6b48f6507a6da403a274fe201595edc86a84463d50383d07f64bdde2e3658108db7d6dc87

    - name: Disable 'pve-enterprise' repository
      ansible.builtin.apt_repository:
        repo: "deb https://enterprise.proxmox.com/{{ ansible_distribution|lower }}/pve {{ ansible_distribution_release|lower }} pve-enterprise"
        state: absent
        filename: /etc/apt/sources.list.d/pve-enterprise.list
    - name: Enable 'pve-no-subscription' repository
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/{{ ansible_distribution|lower }}/pve {{ ansible_distribution_release|lower }} pve-no-subscription"
        state: present
        filename: pve-install-repo
    - name: Correct 'ceph' package sources
      block:
        - ansible.builtin.apt_repository:
            repo: "deb https://enterprise.proxmox.com/{{ ansible_distribution|lower }}/ceph-squid {{ ansible_distribution_release|lower }} enterprise"
            state: absent
            filename: ceph
        - ansible.builtin.apt_repository:
            repo: "deb http://download.proxmox.com/{{ ansible_distribution|lower }}/ceph-squid {{ ansible_distribution_release|lower }} no-subscription"
            state: present
            filename: ceph
    - name: Disable 'pvetest' repository
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/{{ ansible_distribution|lower }}/pve {{ ansible_distribution_release|lower }} pvetest"
        state: absent
        filename: pvetest-for-beta.list

- name: Add additional APT repositories
  when: ansible_os_family == 'Debian'
  become: true
  block:
    - name: Add Docker APT repository
      ansible.builtin.deb822_repository:
        name: docker
        state: present
        types: [deb]
        uris: "https://download.docker.com/linux/{{ ansible_distribution|lower }}"
        suites: ["{{ ansible_distribution_release|lower }}"]
        components: [stable]
        signed_by: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
        enabled: yes

    - name: Add Tailscale stable APT repository
      ansible.builtin.deb822_repository:
        name: tailscale-stable
        types: [deb]
        uris: "https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower }}"
        signed_by: "https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower }}/{{ ansible_distribution_release|lower }}.noarmor.gpg"
        suites: ["{{ ansible_distribution_release|lower }}"]
        components: [main]
        state: present
        enabled: yes
