---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    # HTTPRoute hostname
    - select:
        kind: HTTPRoute
        name: audiobookshelf
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
    - select:
        kind: HTTPRoute
        name: audiobookshelf-redirect
      fieldPaths:
        - spec.hostnames.0
        - spec.rules.0.filters.0.requestRedirect.hostname
      options:
        delimiter: "."
        index: 1
    - select:
        kind: HTTPRoute
        name: audiobookshelf-audiobooks-redirect
      fieldPaths:
        - spec.hostnames.0
        - spec.rules.0.filters.0.requestRedirect.hostname
      options:
        delimiter: "."
        index: 1
