---
image:
  # sharevb/it-tools is forked from CorentinTh/it-tools
  # Link: https://github.com/sharevb/it-tools
  repository: ghcr.io/sharevb/it-tools
  pullPolicy: IfNotPresent
  tag: 2026.7.11@sha256:5d79e8c7fbf39d6473c282b9c4f86ff85c4900ec22ef766ae3c6f0f9ca8dbb37
podOptions:
  hostUsers: false
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
  config:
    enabled: true
    type: emptyDir
    mountPath: /config
