---
image:
  # sharevb/it-tools is forked from CorentinTh/it-tools
  # Link: https://github.com/sharevb/it-tools
  repository: ghcr.io/sharevb/it-tools
  pullPolicy: IfNotPresent
  tag: 2026.1.4@sha256:6d335b5d6f7d28a540ef36c0ab2e20cbf7df2c0d8b7adb16585ccd3ebcfeed59
podOptions:
  hostUsers: false
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
  config:
    enabled: true
    type: emptyDir
    mountPath: /config
