---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: version-checker
    namespace: version-checker
    releaseName: version-checker
    repo: https://charts.jetstack.io
    valuesFile: ../../base/values.yaml
    version: 0.9.3
