---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: version-checker
    repo: https://charts.jetstack.io
    version: v0.11.0
    releaseName: version-checker
    namespace: version-checker
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
