---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: authservice-cyberchef-secret-store
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-system
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
      remoteNamespace: cyberchef
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authservice-cyberchef-secret-store
  namespace: cyberchef
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authservice-cyberchef-secret-store
  namespace: cyberchef
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authservice-cyberchef-secret-store
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
