---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: prowlarr
    repo: oci://oci.trueforge.org/truecharts
    version: 22.7.0
    releaseName: prowlarr
    namespace: servarr
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars-prowlarr
    envs:
      - /tmp/env-vars.env
replacements:
  - path: replacements.yaml
