---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: floppy-postgres
  namespace: floppy
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  postgresql:
    pg_hba:
      - hostssl floppy floppy all scram-sha-256
      - host floppy floppy all reject
  bootstrap:
    recovery:
      source: clusterBackup
  externalClusters:
    - name: clusterBackup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: cnpg-backups
          serverName: floppy-postgres
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  storage:
    size: 4Gi
    storageClass: longhorn-cnpg
  resources:
    requests:
      cpu: 20m
      memory: 160Mi
    limits:
      memory: 512Mi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-backups
