---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    postgresql.cnpg.homelab.towerofkubes.com/barman-server-name: floppy-postgres
  name: floppy-postgres
  namespace: floppy
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  postgresql:
    pg_hba:
      - hostssl floppy floppy all scram-sha-256
      - host floppy floppy all reject
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  storage:
    size: 4Gi
    storageClass: longhorn-cnpg
  resources:
    requests:
      cpu: 20m
      memory: 160Mi
    limits:
      memory: 512Mi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-backups
  bootstrap:
    initdb:
      database: floppy
      owner: floppy
