- name: Delete API token 'provider' for user 'terraformer@pve'
  ansible.builtin.command:
    cmd: "pveum user token delete terraformer@pve provider"
  failed_when: false

- name: Create API token 'provider' for user 'terraformer@pve'
  ansible.builtin.command:
    cmd: "pveum user token add terraformer@pve provider --privsep=0"
  register: token_add_result
  failed_when: token_add_result.rc != 0 and 'already exists' not in token_add_result.stderr
  changed_when: "'already exists' not in token_add_result.stderr"

- name: Get API token
  when: token_add_result.changed
  block:
  - name: Output API token info
    ansible.builtin.debug:
      msg: "{{ token_add_result.stdout_lines }}"

  - name: Extract full-tokenid and value from stdout
    set_fact:
      full_tokenid: "{{ (token_add_result.stdout_lines | select('search', 'full-tokenid') | list | first | default('')) }}"
      token_value: "{{ (token_add_result.stdout_lines | select('search', '^│ value') | list | first | default('')) }}"

  - name: Debug found token lines
    debug:
      var: token_lines
    
  - name: Output formatted Proxmox API token
    debug:
      msg: "{{ full_tokenid }}!token={{ token_value }}"
