apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-wildcard
spec:
  secretName: tls-wildcard
  dnsNames:
    - "*.${FQDN_01}"
    - "${FQDN_01}"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kanidm,istio-ingress,default"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kanidm,istio-ingress,default"
