---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: miniflux
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: http-gateway-api
      namespace: envoy-gateway-ingress
  hostnames:
    - "miniflux.${FQDN_01}"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: miniflux
          namespace: miniflux
          port: 10091
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
