---
- name: Configure btrfs subvolume
  become: true
  block:
    - name: Ensure btrfs tools are installed
      ansible.builtin.package:
        name: btrfs-progs
        state: present

    - name: Mount BTRFS root to create parent directories
      ansible.posix.mount:
        src: "{{ btrfs_filesystem_device }}"
        path: /mnt/btrfs-root
        opts: subvolid=5
        fstype: btrfs
        state: ephemeral

    - name: Create parent directory structure in BTRFS root
      ansible.builtin.file:
        path: /mnt/btrfs-root/var/lib/pve
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Unmount BTRFS root
      ansible.posix.mount:
        path: /mnt/btrfs-root
        state: unmounted

    - name: Create the btrfs subvolume
      community.general.btrfs_subvolume:
        name: "{{ btrfs_subvol_path }}"
        filesystem_device: "{{ btrfs_filesystem_device }}"
        state: present
        automount: true

    - name: Ensure mount point exists in running system
      ansible.builtin.file:
        path: "/{{ btrfs_subvol_path }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Mount the btrfs subvolume
      ansible.posix.mount:
        src: "{{ btrfs_filesystem_device }}"
        path: "/{{ btrfs_subvol_path }}"
        opts: "subvol={{ btrfs_subvol_path }},compress=zstd:1"
        fstype: btrfs
        state: mounted
