---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: valkey-operator
    repo: oci://ghcr.io/sap/valkey-operator-helm
    version: 0.1.4
    releaseName: valkey-operator
    namespace: valkey-operator
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
