---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: reloader
    repo: oci://ghcr.io/stakater/charts
    version: 2.1.3
    releaseName: reloader
    namespace: kube-system
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
