---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: node-feature-discovery
    repo: oci://registry.k8s.io/nfd/charts
    version: 0.19.0
    releaseName: node-feature-discovery
    namespace: node-feature-discovery
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
