---
kustomize_overlays:
  - name: cert-manager
    set: addons
    overlay: bootstrap
    wait: true
  - name: cert-resources
    set: resources
    overlay: bootstrap
    wait: true
  - name: external-secrets
    set: addons
    overlay: bootstrap
    wait: false
  - name: argocd
    set: argo
    overlay: bootstrap
    wait: false
kubernetes_manifests:
  - name: app-of-apps
    file: bootstrap/app-of-apps.yaml
    wait: true
