---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-lb-pool
spec:
  blocks:
    - start: 192.168.1.50
      stop: 192.168.1.50
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: envoy-gateway-ingress
      io.kubernetes.service.name: http-gateway-api
