---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-lb-pool
spec:
  blocks:
    - start: 192.168.1.60
      stop: 192.168.1.60
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: istio-ingress
      io.kubernetes.service.name: istio-ingressgateway
