---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # - service-monitor.yaml
patches:
  - target:
      kind: RoleBinding
      name: events:kubelet-serving-cert-approver
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kubelet-serving-cert-approver
