---
persistence:
  media:
    existingClaim: smb-mediadata-rwx
    advancedMounts:
      audiobookshelf:
        app:
          - path: /books
            subPath: Media/Books
            readOnly: false
          - path: /podcasts
            subPath: Media/Audio/Podcasts
            readOnly: false
rawResources:
  smb-mediadata-rwx:
    apiVersion: v1
    kind: PersistentVolumeClaim
    forceRename: smb-mediadata-rwx
    spec:
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: smb-mediadata
        resources:
          requests:
            storage: 100Ti
  # httproute:
  #   apiVersion: gateway.networking.k8s.io/v1
  #   kind: HTTPRoute
  #   forceRename: audiobookshelf
  #   annotations:
  #     gethomepage.dev/enabled: "true"
  #     gethomepage.dev/description: Audiobooks, Books and Podcasts
  #     gethomepage.dev/group: Media
  #     gethomepage.dev/icon: audiobookshelf.svg
  #     gethomepage.dev/name: audiobookshelf
  #     gethomepage.dev/pod-selector: "app.kubernetes.io/instance=audiobookshelf"
  #   spec:
  #     spec:
  #       parentRefs:
  #         - group: gateway.networking.k8s.io
  #           kind: Gateway
  #           name: http-gateway-api
  #           namespace: envoy-gateway-ingress
  #       hostnames:
  #         - "audiobookshelf.${FQDN_01}"
  #       rules:
  #         - backendRefs:
  #             - group: ""
  #               kind: Service
  #               name: audiobookshelf
  #               namespace: audiobookshelf
  #               port: &port 80
  #               weight: 1
  #           matches:
  #             - path:
  #                 type: PathPrefix
  #                 value: /
