---
global:
  createDefaultServiceAccount: false
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault
controllers:
  papra:
    containers:
      papra:
        image:
          repository: ghcr.io/papra-hq/papra
          tag: 26.6.1-rootless@sha256:a7a42e228f73f229d1e2dcd53de7b67503f1756d1aa3a894ab175dba8030c0e8
        probes:
          liveness: &probes
            enabled: true
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 25m
            memory: 256Mi
          limits:
            memory: 512Mi
service:
  papra:
    controller: papra
    ports:
      http:
        port: 1221
persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: "/app/app-data"
  ingestion:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: "/app/ingestion"
  tmp:
    type: emptyDir
    globalMounts:
      - path: "/tmp"
