---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    # HTTPRoute hostname
    - select:
        kind: HTTPRoute
        name: bentopdf
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
