---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secrets
  - database/cloudnative-pg.yaml
  - resources/seerr-settings.yaml
  - resources/httproute-gate-rbac.yaml
  - resources/httproute-gate-job.yaml
  - resources/httproute.yaml
helmCharts:
  - name: seerr-chart
    repo: oci://ghcr.io/seerr-team/seerr
    version: 3.6.0
    releaseName: seerr
    namespace: seerr
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars-seerr
    envs:
      - /tmp/env-vars.env
replacements:
  - path: replacements.yaml
patches:
  - path: patches/statefulset-bootstrap-settings.yaml
