---
ingress:
  enabled: true
  ingressClassName: tailscale
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Request management and media discovery for Jellyfin.
    gethomepage.dev/group: Servarr
    gethomepage.dev/icon: overseerr.svg
    gethomepage.dev/name: Seerr
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance=seerr"
    gethomepage.dev/widget.type: "jellyseerr"
    gethomepage.dev/widget.url: "http://seerr.seerr.svc.cluster.local:80"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SEERR_KEY}}"
  hosts:
    - host: "get.${FQDN_02}"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "get.${FQDN_02}"

route:
  main:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: http-gateway-api
        namespace: istio-ingress
    hostnames:
      - "get.${FQDN_01}"
