---
ingress:
  enabled: true
  ingressClassName: tailscale
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Request management and media discovery for Jellyfin.
    gethomepage.dev/group: Servarr
    gethomepage.dev/icon: overseerr.svg
    gethomepage.dev/name: Seerr
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance=seerr"
    gethomepage.dev/widget.type: "jellyseerr"
    gethomepage.dev/widget.url: "http://seerr.seerr.svc.cluster.local:80"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SEERR_KEY}}"
  hosts:
    - host: "seerr.${FQDN_02}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "seerr.${FQDN_02}"

extraEnv:
  - name: API_KEY
    valueFrom:
      secretKeyRef:
        name: seerr-secrets
        key: SEERR_API_KEY
  - name: DB_TYPE
    value: postgres
  - name: DB_LOG_QUERIES
    value: "false"
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: host
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: port
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: user
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: dbname

route:
  main:
    enabled: false
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: http-gateway-api
        namespace: istio-ingress
    hostnames:
      - "get.${FQDN_01}"
