---
podAnnotations:
  secret.reloader.stakater.com/reload: "seerr-kanidm-oauth2-credentials,seerr-postgres-app,seerr-secrets,seerr-servarr-secrets"
  configmap.reloader.stakater.com/reload: "seerr-settings"

extraEnv:
  - name: API_KEY
    valueFrom:
      secretKeyRef:
        name: seerr-secrets
        key: seerr_api_key
  - name: DB_TYPE
    value: postgres
  - name: DB_LOG_QUERIES
    value: "false"
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: host
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: port
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: user
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: password
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: seerr-postgres-app
        key: dbname

volumes:
  - name: seerr-settings
    configMap:
      name: seerr-settings

ingress:
  enabled: true
  ingressClassName: tailscale
  annotations:
    tailscale.com/proxy-group: ingress-proxies
  hosts:
    - host: "seerr.${FQDN_02}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "seerr.${FQDN_02}"

route:
  main:
    enabled: false
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: http-gateway-api
        namespace: istio-ingress
    hostnames:
      - "get.${FQDN_01}"
