---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: ingress-nginx
    namespace: ingress-nginx
    releaseName: ingress-nginx
    repo: oci://ghcr.io/home-operations/charts-mirror
    valuesFile: ../../base/values.yaml
    version: 4.12.3
