---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    "../../base",
  ],
  helmCharts: [{
    name: "ingress-nginx",
    repo: "oci://ghcr.io/home-operations/charts-mirror",
    version: "4.12.3",
    releaseName: "ingress-nginx",
    namespace: "ingress-nginx",
    valuesFile: "../../base/values.yaml",
    additionalValuesFiles: [
      "values.yaml",
    ],
  }],
}
