---
{
  defaultBackend: {
    enabled: true,
  },
  controller: {
    service: {
      type: "ClusterIP",
    },
    extraArgs: {
      default-ssl-certificate: "certificates/tls-wildcard",
      enable-ssl-passthrough: "",
    },
    config: {
      # https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/
      enable-modsecurity: "true",
      enable-owasp-modsecurity-crs: "true",
    },
  },
}
