---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/databases
  - resources/external-secrets
  - resources/storage
components:
  - ../../../../../../../components/cnpg-backup
patches:
  - target:
      kind: ObjectStore
      name: cnpg-backups
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: s3://k8s-backups/cnpg/servarr
