---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/resources/storage/pvc-smb-mediadata-rox.yaml
  - ../../base/resources/storage/pvc-smb-mediadata-rwx.yaml
