---
podOptions:
  hostUsers: true
workload:
  main:
    podSpec:
      containers:
        main:
          # https://github.com/alexta69/metube?tab=readme-ov-file#%EF%B8%8F-configuration-via-environment-variables
          env:
            MAX_CONCURRENT_DOWNLOADS: 3
            DELETE_FILE_ON_TRASHCAN: true
            CLEAR_COMPLETED_AFTER: 86400  # 24 hours
            # Playlist details, author, UNIX filename sanitization:
            # Link: https://github.com/alexta69/metube/wiki/YTDL_OPTIONS-Cookbook
            # yamllint disable-line rule:line-length
            OUTPUT_TEMPLATE: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S - %(title|UNKNOWN_TITLE)S - %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S.%(ext)s'
            YTDL_OPTIONS: '{"writesubtitles": true, "writeautomaticsub": true, "subtitleslangs": ["^en(?!-en-).*", "^he(?!-he-).*"], "postprocessors": [{"key": "FFmpegEmbedSubtitle"}]}'
