---
podOptions:
  hostUsers: true
workload:
  main:
    podSpec:
      containers:
        main:
          # https://github.com/alexta69/metube?tab=readme-ov-file#%EF%B8%8F-configuration-via-environment-variables
          env:
            ALLOW_YTDL_OPTIONS_OVERRIDES: false
            CORS_ALLOWED_ORIGINS: "*" # allow browser extensions and bookmarklets
            MAX_CONCURRENT_DOWNLOADS: 3
            DELETE_FILE_ON_TRASHCAN: true
            CLEAR_COMPLETED_AFTER: 86400  # 24 hours
            # yamllint disable rule:line-length
            # Playlist details, author, UNIX filename sanitization:
            # Link: https://github.com/alexta69/metube/wiki/YTDL_OPTIONS-Cookbook
            OUTPUT_TEMPLATE: '%(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S - %(title|UNKNOWN_TITLE)S - %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S.%(ext)s'
            # English subtitles & chapter marks, permissions, modification timestamp
            # Link: https://github.com/alexta69/metube/wiki/YTDL_OPTIONS-Cookbook
            YTDL_OPTIONS: '{"writesubtitles": true, "writeautomaticsub": true, "subtitleslangs": ["en", "he", "-live_chat"], "updatetime": false, "postprocessors": [{"key": "Exec", "exec_cmd": "chmod 0664", "when": "after_move"}, {"key": "FFmpegEmbedSubtitle", "already_have_subtitle": false}, {"key": "FFmpegMetadata", "add_chapters": true}]}'
            # SponsorBlock Preset
            # Link: https://github.com/alexta69/metube#presets
            YTDL_OPTIONS_PRESETS: '{"sponsorblock": {"postprocessors": [{"key": "SponsorBlock", "categories": ["sponsor"]}, {"key": "ModifyChapters", "remove_sponsor_segments": ["sponsor"]}]}}'
            # yamllint enable rule:line-length
