---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "cloudflare-operator-system",
  resources: [
    "resources/external-secrets/cloudflare-operator.yaml.externalsecret",
    "resources/external-secrets/cloudflare-dns.yaml.externalsecret",
  ],
}
