---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - object-store.yaml
  - scheduled-backup.yaml
replacements:
  - source:
      kind: Cluster
      fieldPath: metadata.name
    targets:
      - select:
          kind: ScheduledBackup
          name: cnpg-backup
        fieldPaths:
          - spec.cluster.name
        options:
          create: true
