---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-backups
spec:
  configuration:
    destinationPath: "s3://k8s-backups/cnpg"
    s3Credentials:
      accessKeyId:
        name: cnpg-backup-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-backup-secret
        key: AWS_SECRET_ACCESS_KEY
      region:
        name: cnpg-backup-secret
        key: AWS_REGION
    data:
      compression: zstd
    wal:
      compression: zstd
      maxParallel: 1
  retentionPolicy: "7d"
  instanceSidecarConfiguration:
    env:
      - name: AWS_ENDPOINT_URL
        valueFrom:
          secretKeyRef:
            name: cnpg-backup-secret
            key: AWS_ENDPOINT_URL
