---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: coredns
    namespace: kube-system
    releaseName: coredns
    repo: oci://ghcr.io/coredns/charts
    valuesFile: ../../base/values.yaml
    version: 1.43.3
