---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: coredns
    repo: oci://ghcr.io/coredns/charts
    version: 1.45.2
    releaseName: coredns
    namespace: kube-system
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
configMapGenerator:
  - name: env-vars
    envs:
      - /tmp/env-vars.env
  - name: coredns-rewrite-rules
    literals:
      - REWRITE_RULE=name regex (^|.*[.])(?:)FQDN_01_REGEX(?:)(?:$|[.]$|[.]cluster[.]local[.]?$|[.](?:[a-z0-9-]+[.])?svc[.]cluster[.]local[.]?$) http-gateway-api.envoy-gateway-ingress.svc.cluster.local.
replacements:
  - path: replacements.yaml
