---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-kubernetes-secret-store-serviceaccount.yaml
  - argocd-kubernetes-secret-store.yaml
  - argocd-kubernetes-secret-store-rbac.yaml
  - git-webhook.yaml.externalsecret
  - oidc-credentials.yaml.externalsecret
