---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-wildcard
spec:
  secretName: tls-wildcard
  dnsNames:
    - "*.${FQDN_01}"
    - "${FQDN_01}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  duration: 160h
  usages: ["digital signature"]
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-ingress,kaniop"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-ingress,kaniop"
