---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: intel-gpu-resource-driver
    repo: oci://ghcr.io/intel/intel-resource-drivers-for-kubernetes
    version: 0.8.0
    releaseName: intel-gpu-resource-driver
    namespace: intel-gpu
    includeCRDs: true
    valuesFile: values-override.yaml
