---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: intel-gpu-resource-driver-chart
    namespace: intel-gpu
    releaseName: intel-gpu-resource-driver
    repo: oci://ghcr.io/intel/intel-resource-drivers-for-kubernetes
    valuesFile: ../../base/values.yaml
    version: 0.9.0
