---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idm-tls
spec:
  secretName: idm-tls
  dnsNames:
    - "id.${FQDN_01}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
