---
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: idm
spec:
  domain: "auth.${FQDN_01}"
  tlsSecretName: tls-wildcard
  volumes:
    - name: override-css
      configMap:
        name: kanidm-ui-override-css
        items:
          - key: override.css
            path: override.css
  volumeMounts:
    - name: override-css
      mountPath: /hpkg/override.css
      subPath: override.css
      readOnly: true
  oauth2ClientNamespaceSelector:
    matchLabels: {}  # Watch all namespaces
  replicaGroups:
    - name: default
      replicas: 1
      primaryNode: true
      statefulSetAnnotations:
        configmap.reloader.stakater.com/reload: "kanidm-ui-override-css"
        secret.reloader.stakater.com/reload: "tls-wildcard"
  logLevel: info
  # Enable LDAPS service on port 3636
  # Kanidm uses its TLS certificates for both HTTPS and LDAPS
  ldapPortName: ldaps
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
  personNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kaniop-resources
  groupNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kaniop-resources
