---
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: idm
spec:
  domain: "id.${FQDN_01}"
  tlsSecretName: tls-wildcard
  oauth2ClientNamespaceSelector:
    matchLabels: {}  # Watch all namespaces
  replicaGroups:
    - name: default
      replicas: 1
      primaryNode: true
  logLevel: info
  # Enable LDAPS service on port 3636
  # Kanidm uses its TLS certificates for both HTTPS and LDAPS
  ldapPortName: ldaps
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
