---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: "data.FQDN_01"
  targets:
    - select:
        kind: Kanidm
        name: idm
      fieldPaths:
        - spec.domain
      options:
        delimiter: "."
        index: 1
    - select:
        kind: HTTPRoute
        name: idm
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
