---
- source:
    kind: ConfigMap
    name: env-vars-immich
    fieldPath: "data.FQDN_01"
  targets:
    - select:
        kind: HTTPRoute
        name: immich
      fieldPaths:
        - spec.hostnames.0
      options:
        delimiter: "."
        index: 1
    - select:
        kind: Secret
        name: env-vars
      fieldPaths:
        - stringData.FQDN_01
