---
# renovate: datasource=github-releases depName=immich-app/immich
immichVersion: v2.6.3

defaultPodOptions:
  annotations:
    secret.reloader.stakater.com/reload: immich-database-app

controllers:
  main:
    containers:
      main:
        image:
          tag: '{{ .Values.immichVersion }}'
        env: &immichCommonEnv
          REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
          IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
          DB_URL:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: uri
          DB_VECTOR_EXTENSION: vectorchord
          IMMICH_ALLOW_SETUP: false

server:
  enabled: true
  controllers:
    main:
      containers:
        main:
          env:
            IMMICH_WORKERS_INCLUDE: api
    microservices:
      type: deployment
      containers:
        main:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: '{{ .Values.immichVersion }}'
          env:
            <<: *immichCommonEnv
            IMMICH_WORKERS_EXCLUDE: api

immich:
  persistence:
    library:
      existingClaim: immich-library

valkey:
  enabled: true

machine-learning:
  enabled: true
  controllers:
    main:
      containers:
        main:
          image:
            tag: '{{ .Values.immichVersion }}-openvino'
