---
apt_packages:
# Docker packages
- containerd.io
- docker-buildx-plugin
- docker-ce
- docker-ce-cli
- docker-ce-rootless-extras
- docker-compose-plugin
# Proxmox packages
- proxmox-default-kernel
- proxmox-ve
- postfix
- open-iscsi
- chrony
- proxmox-kernel-6.14 # https://forum.proxmox.com/tags/opt-in-kernel/

dnf_packages:
- containerd.io
- docker-buildx-plugin
- docker-ce
- docker-ce-cli
- docker-ce-rootless-extras
- docker-compose-plugin
