---
name: ShellCheck
'on':
  push:
    branches: [main]
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  shellcheck:
    name: ShellCheck
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v6
      - name: Install xz-utils
        run: sudo apt-get update -qq && sudo apt-get install --assume-yes -qq xz-utils
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          format: gcc
