---
name: yamllint
'on':
  pull_request:
    paths:
      - '**/yaml'
      - '**/yml'
      - '.github/workflows/yamllint.yml'
  push:
    branches: [main]
    paths:
      - '**/yaml'
      - '**/yml'
      - '.github/workflows/yamllint.yml'
  workflow_dispatch:
jobs:
  yamllint:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install wget
        shell: sh
        run: sudo apt-get update -qq && sudo apt-get install --assume-yes -qq wget
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          check-latest: true
      - name: Install yamllint
        run: python3 -m pip install yamllint
      - name: List all YAML files
        shell: sh
        run: |
          yamllint . --list-files
      - name: Lint all YAML files
        shell: sh
        run: |
          find . \
          -type f \( -name '*.yaml' -o -name '*.yml' \) -print0 \
          | xargs -0 yamllint -c .yamllint.yml
      - name: ansible-lint for `ansible/pve-single-node`
        uses: ansible/ansible-lint@v26
        with:
          args: "--profile=min"
          setup_python: "false"
          working_directory: "ansible/pve-single-node"
          requirements_file: "requirements.yml"
      - name: ansible-lint for `ansible/pve-cluster`
        uses: ansible/ansible-lint@v26
        with:
          args: "--profile=min"
          setup_python: "false"
          working_directory: "ansible/pve-cluster"
          requirements_file: "requirements.yml"
      - name: ansible-lint for `ansible/ansible-k8s`
        uses: ansible/ansible-lint@v26
        with:
          args: "--profile=min"
          setup_python: "false"
          working_directory: "ansible/ansible-k8s"
          requirements_file: "requirements.yml"
