---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - additionalValuesFiles:
      - values-override.yaml
    includeCRDs: true
    name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: oci://quay.io/jetstack/charts
    valuesFile: ../../base/values.yaml
    version: v1.18.2
