---
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: data.FQDN_01
  targets:
    - select:
        kind: Service
        name: http-gateway-api
      fieldPaths:
        - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
      options:
        delimiter: ","
        index: 0
- source:
    kind: ConfigMap
    name: env-vars
    fieldPath: data.FQDN_01
  targets:
    - select:
        kind: Service
        name: http-gateway-api
      fieldPaths:
        - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
      options:
        delimiter: ",*."
        index: 1
