---
persistence:
  tmp:
    type: emptyDir
    advancedMounts:
      floppy:
        app:
          - path: "/tmp"
        mcp-1:
          - path: "/tmp"
        mcp-2:
          - path: "/tmp"
  postgres-ca:
    type: secret
    name: floppy-postgres-ca
    advancedMounts:
      floppy:
        app:
          - path: "/postgres-ca"
            readOnly: true
        wait-for-postgres:
          - path: "/postgres-ca"
            readOnly: true
  valkey-data:
    type: emptyDir
    advancedMounts:
      valkey:
        app:
          - path: "/data"
